### ISSUE TITLE
Empty mailto link

### ISSUE THREAD

**Issue by liamsi** [Rustaceans/rust-cologne#1]
Hi,
regarding this [mailto](https://github.com/Rustaceans/rust-cologne/blob/gh-pages/index.html#L24): I created a gmail account for our meetup some time ago (rust.cologne@gmail.com). Should we use this or would you prefer the meetup mailing list (Rust-Cologne-list@meetup.com)? I would prefer the first option (gmail), as meetup by default sends a lot of mails... What would you prefer? cc: @brakmic , @killercup

**Comment by killercup** [comment]
I would prefer your rust.cologne@gmail.com account as well (assuming you read it :wink:), just so we don't depend on meetup.com for that.

(Feel free to add that `email` value in the config file if we all agree.)

**Comment by liamsi** [comment]
Yes, I do :-) And I wrote you a message regarding the group's mails/twitter account etc.

**Comment by killercup** [comment]
@Liamsi I just added the gmail address. Feel free to change this later :)

**Comment by liamsi** [comment]
Hi, thanks a lot. Sorry, I am extremely busy since weeks. But I hope to
able to give this repo and the user group some more attention again soon.
Cheers,
Ismail
Am 26.08.2015 20:26 schrieb "Pascal Hertleif" notifications@github.com:
