### ISSUE TITLE
Meetup November 2016

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#10]
~~t.d.b.~~

**Update from after the meetup:** I still want to collect the following stuff before closing this issue:

- [x] Agenda notes: http://cologne.linuxaudio.org/doku.php?id=protokoll_2016_11_16
- [x] @danielappelt's slides: https://danielappelt.github.io/talk-real-time-audio-programming/
- [x] @masche842's slides

**Update (2016-10-06):** At the October meetup, we decided to _not_ do a meetup on the first Wednesday of November, but instead join forces with the Open Source Audio Meetup.

This means our orga plan may a bit different this time around. To not miss anything, I've still cargo-culted the todos from the October meetup here:
- [x] Settle for a date: **2016-11-16**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline 2016-11-02)
  - [x] meetup (http://www.meetup.com/RustCologne/events/234651810/)
  - [x] website (http://rust.cologne/2016/11/16/audio-meetup.html)
  - [x] twitter (https://twitter.com/RustCologne/status/794953839501836288)
  - [x] community calendar
  - [x] reddit (https://www.reddit.com/r/rust/comments/5bgnqv/)
  - [x] rust-lang forum (https://users.rust-lang.org/t/7904)
  - [x] rustplatz (https://forum.rustplatz.de/t/184)

# Invitation draft

```markdown
Title: CGN #12: Rust Audio Special

On **2016-11-16** we will have a Rust Audio Special by combining our
Rust meetup with the Open Source Audio meetup.

Agenda
* Requirements of Real-Time Audio Programming by @danielappelt
* Low Latency Audio Transfer with AES-67¹ and Rust by @masche842
* open discussion about music, audio software and programming with Rust

You can enjoy some drinks, meet nice people and discuss about Rust and Open Source Audio.
Be prepared for an interesting mix of topics from both worlds.

**[You can register here](http://www.meetup.com/RustCologne/events/234651810/)**.

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin
―  
IMPORTANT NOTE: **This meetup will be held in German** - _not English_ -
due to joining with the Open Source Audio meetup.

PS: Make sure to also check out our other great
[Weekend Special: Novemb.rs Code Sprint sponsored by Mozilla](http://www.meetup.com/RustCologne/events/235374218/)
three days later from **Saturday 2016-11-19 to Sunday 20th**.

¹: **AES-67** is an open standard for reliable audio data transport with very low latency
(real-time). Since its publication in 2013 it has been implemented by many manufacturers
but still lacks an open source implementation so far.
```
# Rust News
- [Rust Language Server (pre-alpha source release)](https://internals.rust-lang.org/t/introducing-rust-language-server-source-release/4209)
-> [GNOME Builder IDE now supports Rust via Rust Language Service](https://blogs.gnome.org/chergert/2016/10/25/builder-rust/)
- Mozilla announced [Project Quantum](https://wiki.mozilla.org/Quantum): Adopting more Servo code in Firefox, which is highly parallelized like CSS handling and GPU rendering
- [cargo-update](https://docs.rs/cargo-update). A cargo subcommand for checking and applying updates to installed executables.
- [Rust 1.13 released](https://github.com/rust-lang/rust/blob/master/RELEASES.md) (on Nov 11)
-> the `?` operator :-)

**Comment by killercup** [comment]
At Rustfest, @masche842 mentioned that he'd be in Cologne on 16 Nov. This is the _third_ Wednesday in November.

@Rustaceans/organizers-cologne, should we move the meetup to 2016-11-16?

**Comment by Florob** [comment]
The [Open Source Audio Meeting Cologne](http://cologne.linuxaudio.org/doku.php) is at the C4 on that date. They usually occupy the smaller room, but I'd not be too happy with that conflict (I usually participate there too).
Judging by @masche842's profile, it might be worthwhile to join forces and do a audio-themed Rust/Rust-themed Audio Meetup. Thoughts?

cc @hilbrichtsoftware

**Comment by diovudau** [comment]
I think doing one meeting together is a good idea and I would very much
like to do that.

The Audio Meeting is 19:00. Is that compatible?

Greetings,

Nils
info@hilbricht.com

**Comment by colin-kiegel** [comment]
yes, we usually meet at 19:15.

@hilbrichtsoftware What about a monday alternatively? Would that work for you too? (Since wednesdays are not perfect for _all_ of our participants including myself we should try to pick another day once in a while...)

**Comment by diovudau** [comment]
Our meetings dates and times are fixed for the whole year. The
suggestion for collaboration is based on a conflicting date.

Nils

**Comment by colin-kiegel** [comment]
@hilbrichtsoftware oops, my intention was to ask @masche842 .. sorry for the confusion.. :-)

@masche842 What about a monday alternatively? Would that work for you too?

**Comment by masche842** [comment]
@colin-kiegel I'm attending a conference from November 17th to 20th and arrive the day before (Nov 16th). That's why @killercup and I came up with that date. 

If it doesn't work for one or the other reason just leave things as they are. Maybe I'll just have a beer with Pascal then. 

That being said I really like the idea of a combined audio-linux-rust meetup as my main area of work are ethernet based audio networks with a focus on open standards (namely AVB and AES67). But as I said: It has to work for you guys!

**Comment by Florob** [comment]
FWIW, if we don't find another room we can't switch to a Monday in November anyway. The C4 will be occupied by the annual U23 project. Slightly less importantly I will be occupied with that project on Mondays, too.

**Comment by xetra11** [comment]
I'd like to hear some audio stuff as well. Never ever attacked this domain. But I hope sb. has time to get rid of my lifetime parameter problem, too :palm_tree:

**Comment by colin-kiegel** [comment]
Ok, I was just figuring out all alternatives we have. So it's either:
- 2016-11-16 - combined meeting with OS Audio Meeting Cologne (currently preferred choice)
- 2016-11-02 - stand-alone Rust meeting as usual

The combined meeting sounds interesting.. however it will probably involve a bit more effort to come up with a synchronized agenda. @Florob afaik you are the only one who knows both meetings. Therefore I think your suggestions and opinions will be very valuable. Would you like to sketch out a rough agenda proposal or something else? Or how else could we proceed from here with the organization? :-)

@hilbrichtsoftware usually we are between 14-20 people, we start with introducing each one very briefly and then procede with whatever agenda we have come up with. We cap registrations at 20 people in advance.

EDIT: fixed date. :-)

**Comment by Florob** [comment]
@colin-kiegel The date for a combined meetup would be 2016-11-16.

I can try and come up with an agenda later. I think the usual rough agendas of the meetups line up to some extend anyway.

@masche842 Can we talk you into giving a short talk about AES67/rs_sixty_seven? I think that would be interesting to people. If you have something else related you'd rather want to talk about we'd be happy to hear that too ;) (assuming we converge on the 16th of course)

**Comment by killercup** [comment]
What an awesome coincidence! :)

Re: combining the meetups: I wouldn't mind, but there are a few things to consider.

Contra
- I don't want us to overrun the audio meetup.
- If someone wants to give a talk about non-lexical borrowing or Rust's documentation style, we can say yes

Pro
- Less planning :)
- Potentially more people compared to splitting up the number of possible attendees over two dates.

**Comment by colin-kiegel** [comment]
We could make a poll to test if there is more interest in our group in a combined or separate meetup. In the latter case @masche842 @killercup and others from our community could still join the os audio meetup. If instead we do the combined meetup we could of course set a lower participant limit. I just wanted to point out we should talk about group size before we run into trouble. :-)

@hilbrichtsoftware How large is the audio meetup usually? Would there be interest to talk about programming in general and Rust aspects in particular?

Do we want to have talks or discussions?
Do we want to offer some crash courses for each audience or would that be boring?
..?

**Comment by diovudau** [comment]
We are not than many people. Between 5 and 8.  
Programming is usually an 'ok' topic for the OSAMC, but we have some non-programmers there as well. In case of a co-op meeting they will however expect and accept nothing else than programming stuff. 
Additionally I am confident that I will find an audio topic that appeals to a general interest.

**Comment by masche842** [comment]
@Florob Sure. I'll give a talk about redundancy in audio networks two days later, but there should be time to prepare a lightning talk about rs-sixty-seven anyways. 
As you can see in the repository it is only a stub for now, nonetheless I can still talk about the concepts and the ideas behind it. This may even close the gap between programming and open source related music production technology.

**Comment by killercup** [comment]
We discussed this yesterday, and since a lot of people seemed to be interested in audio as well as rust, we decided to join up with the OS audio meetup at 2016-11-16.

I updated the description of the issue here, and added the event to the website [here](http://rust.cologne/2016/11/16/audio-meetup.html) (description and @masche842's talk details t.b.d.).

**Comment by diovudau** [comment]
All right. I will announce this in our OSAMC October meeting.
If any of you is interested: there are JACK rust bindings.

**Comment by xetra11** [comment]
ah nice mybe the audio meetup will clarify my "Audio Track Templating Engine" question

**Comment by diovudau** [comment]
Are there any members in your rust group that indeed don't speak German? I get it why public communication is in English, but do you usually speak English in your meetings as well? 
OSAMC is in German.

**Comment by badboy** [comment]
No regular attendees, though we have non-german-speaking attendees from time to time. We usually decide at the meeting what language to use. We also advertised it as German-speaking if we knew from speakers beforehand. It's no problem to do this for the joint meetup.

**Comment by killercup** [comment]
Oh, that's an important note! We should make it clear that this meetup is in German, then.

A few of our members prefer English, but not many. At the last meetup there was at least one person who could only understand bits of German and preferred to speak English.

**Comment by colin-kiegel** [comment]
I added a note about it being German over at meetup.

And I started a very early version of an invitation up above in the first post of _this issue_.
@Rustaceans/organizers-cologne Feel free to flesh it out.

EDIT: I think it would be cool if we could announce that a bit earlier than usual, e.g. 10-14 days before the meetup i.e. around 2016-11-02 - what do you think?

**Comment by killercup** [comment]
Invite text looks good. Do you want to say a bit about what topics we expect to talk about? Not everyone might know what Open Source Audio is about and how it relates to Rust.

I'm fine with sending the invite out "early", maybe even in the last week of October. People might expect to hear from us around that time as the regular date (first Wednesday) is November 2nd.

**Comment by colin-kiegel** [comment]
Ok, I filled in the agenda gap with the following suggestion

``` markdown
Agenda
* << TALK >> by @masche842
* open discussion about music, audio software and programming with Rust
```

@masche842 do you have a working title and/or short description for your talk, which we can use to advertise the meetup?

@hilbrichtsoftware should we add anything to our invitation text (see first post) from your perspective?

**Comment by danielappelt** [comment]
I think it is a very good idea to combine both meetups as rust is one of the few languages next to C/C++ that allow for decent real-time audio programming. I am willing to prepare a short high-level talk why that is the case.

**Comment by colin-kiegel** [comment]
@danielappelt cool - let us know if you have a working title, e.g. Audio + Rust = <3 ? ;-)

I think this should be our first talk then.

**Comment by masche842** [comment]
@colin-kiegel I couldn't decide on a language for the abstract so I just wrote both. It is a bit lengthy but hopefully does the job.

Low Latency Audio Transfer with AES-67 and Rust

For quite some time professional audio systems use standard ethernet to transport audio data reliable and with very low latency (real-time). However, as proprietary technology has been used, interoperability was an issue. To resolve this, the Audio Engineering Society (AES) defined a minimal set of requirements in an open standard named AES-67. Since its publication in 2013 it has been implemented by many manufacturers but still lacks an open source implementation. 
Rust on the other hand is a modern system language and seems to be an ideal candidate for this, because it is safe, fast and can be used to develop for many targets from small microcontrollers to full-fledged high performance architectures. 
In this talk I will give a short introduction into real-time networks for professional audio applications and the AES-67 standard. I will then walk through my ideas for an open source implementation called "rs-sixty-seven" and what challenges I see. Finally I like to collect your thoughts and suggestions.

Latenzarme Audioübertragung mit AES-67 und Rust
 Seit langem nutzen Systeme in der professionellen Audioindustrie Standard-Ethernet, um Audiodaten zuverlässig und mit geringer Latenz (in Echtzeit) zu übertragen. Dafür kamen bisher beinahe ausschließlich proprietäre Technologien zum Einsatz, weswegen ein Zusammenspiel nicht möglich gewesen ist. Deshalb hat die Audio Engineering Society (AES) in einem offenen Standard, AES-67, Anforderungen für Interoperabilität zwischen den Systemen spezifiziert. Seit der Veröffentlichung in 2013 sind viele Geräte auf den Markt gekommen, die diesen Standard unterstützen, allerdings gibt es noch keine Open-Source-Implementierung. 
 Die Programmiersprache Rust scheint ein idealer Kandidat zu sein, um eine solche Implementierung zu realisieren, denn sie unterstützt Systeme vom Mikrocontroller bis zum Supercomputer und fördert die Entwicklung schneller und sicherer Programme. 
 Im Vortrag erläutere ich zunächst die Grundlagen von professionellen Audionetzwerken und dem AES-67-Standard. Dann stelle ich meine Ideen für die Implementierung "rs-sixty-seven" vor und welche Herausforderungen ich dabei sehe. Abschließend würde ich mich darüber freuen, Eure Gedanken und Vorschläge dazu zu sammeln.

**Comment by masche842** [comment]
Mmmh, maybe it's not going to be a lightning talk though ;-)

**Comment by diovudau** [comment]
Please try to keep it within 20 minutes followed by 10 minutes for questions.

**Comment by colin-kiegel** [comment]
@masche842 great thank you for the description of your talk. The title is just fine. :-)
I am already excited to hear it. And I updated our invitation draft.

@hilbrichtsoftware do you have any plans what to do after the talks? Technically we are the guests in your Open Source Audio meetup, so I could imagine you having the lead after the talks. Personally I am open to being spontaneous and engaging in either group or individual discussions after the talks. 

@Rustaceans/organizers-cologne what do you think?

Whatever we are going to do we should synchronize our expectations first to avoid confusion during the meetup. :-)

PS: This is basically the third bullet point. It's already in the invitation draft, but we haven't discussed it:
- open discussion about music, audio software and programming with Rust

**Comment by diovudau** [comment]
OSAMC usually has a formal part, which can be seen outlined here http://yourpart.eu/p/linuxaudio-cologne

After the regular points like news, media recommendations and more come the demos and talks. Those always lead into a free discussion which is not moderated and sometimes leads to vastly different topics, which is good.

**Comment by colin-kiegel** [comment]
Sounds good to me. Usually we begin similarly with introducing ourselves and reflecting whats new in Rust. We obviously don't have an equivalent for the flea market. ;-) If we follow your plan, we could just add our whats-new-in-Rust part and would be all good.

**Comment by colin-kiegel** [comment]
PS: I think we should not have more than the two talks already scheduled to allow for some discussion. But that's just my opinion.

**Comment by colin-kiegel** [comment]
@masche842 I think you can/should be very brief on why Rust is well suited for the AES67 implementation since @danielappelt will talk about why Rust is well suited for real time studio... Just to make sure we don't generate too much overlap here.

**Comment by danielappelt** [comment]
@colin-kiegel, it is more likely that my talk will focus on the requirements of real-time audio programming. Only on a high-level, I would like to explain why rust seems to be a better choice for that subject than many other new generation languages.

Currently, my idea is a short motivation, followed by a summary of these two articles:
- [Real-time audio programming 101: time waits for nothing](http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing)
- [Ch. "Inside scsynth" of "The SuperCollider Book"](http://supercolliderbook.net/rossbencinach26.pdf) (just p. 730 :blush:)

For now, I am still searching for a meaningful working title..

**Comment by colin-kiegel** [comment]
@danielappelt we would really like to send out the invitation today, but we don't know the title of your talk.

If we don't get feedback from you today, we will probably go with your stated likely topic and announce it as **requirements of real-time audio programming**. However we would appreciate some short term feedback.

Sorry for the rush. ^^

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I suggest I start sending out the invitations around 18:00 o'clock. I think you all already agreed on the text and the title of the first talk is kind of the lats piece of the puzzle now. ;-)

**Comment by killercup** [comment]
Colin, do you want to include the novembe.rs announcement in that mail as
well? (See my other mail.)

Colin Kiegel notifications@github.com schrieb am Sa. 5. Nov. 2016 um
13:12:

**Comment by colin-kiegel** [comment]
Yeah, I was just about to answer to that in the email where the idea was raised.

My personal tendency would be to have two separate mails - which we could send out semi-simultaneously. In both invitations we could "cross-link" the other invitation like "PS: Checkout our other special event in November: ...". I think this way it would be easier distinguishable and clearer that we have to separate events coming. I know it's two emails this way, but on the other hand we don't have much formatting available in the meetup mails and I am not a big fan of super long mails.

As of twitter / reddit or forums I could imagine to go different routes individually. I would leave that to the person who posts to that specific channel.

But on the other hand if you all prefer "one big mail", I am ok with that too. @badboy @Florob your oppinion?
PS: I'll start drafting a invitation for novemb.rs now.

**Comment by colin-kiegel** [comment]
Just added these bits to the draft

``` markdown
Yours,
Jan-Erik, Pascal, Florob and Colin
```

``` markdown
PS: Make sure to also check out our other great
[novemb.rs Code Sprint Weekend Special](http://www.meetup.com/RustCologne/events/235374218/)
three days later from **Saturday 2016-11-19 to Sunday 20th**.
```

**Comment by killercup** [comment]
Thanks, @colin-kiegel! I don't mind sending two emails, especially if they are automated ones from meetup.com anyway. (The PS text is fine as well. 😄)

There already are some novembe.rs announcements on social media, and they should be separate from (but mentioned in) the next meetup announcement.

**Comment by colin-kiegel** [comment]
Ok, ich habe wieder meetup und die beiden Foren übernommen und für Rustplatz auch wieder auf Deutsch übersetzt..

Will wieder jemand anderes Twitter, Reddit und die Webseite übernehmen? Dankeschön... ;-)

**Comment by colin-kiegel** [comment]
@masche842 @danielappelt Hey guys, someone from the rust user forum [asked](https://users.rust-lang.org/t/cgn-12-rust-audio-special/7904/3?u=colin_kiegel) whether we will publish your presentations. I'm just thinking out loud here: Maybe you could prepare the slides in English and do the talk in German if you are comfortable with it and haven't started the slides in German already. This way a broader audience could enjoy your work afterwards. Of course this is totally up to you and we only publish your slides if you want to. :-)

**Comment by danielappelt** [comment]
@colin-kiegel My presentation is now [online](https://danielappelt.github.io/talk-real-time-audio-programming). See you later!

**Comment by diovudau** [comment]
Das Protokoll von gestern findet sich hier: 
http://cologne.linuxaudio.org/doku.php?id=protokoll_2016_11_16

**Comment by badboy** [comment]
Thanks, @hilbrichtsoftware

**Comment by killercup** [comment]
Thanks for taking notes and linking to the slides, guys!

@masche842, can you send me your slides or a link to them?

**Comment by masche842** [comment]
Was busy with Tonmeistertagung, so it took a little longer. However, here are the slides:
http://schettke.com/files/rs67_rust-cologne_20161115.pdf

It has been a great meetup by the way!

**Comment by killercup** [comment]
Thanks, Marc! I'll add a link to your slides in a minute. I hope you had a great time at the conference!
