### ISSUE TITLE
streamlining our name

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#11]
# What We Settled On

* part of URLs: **RustCologne**
* short title: **Rust Cologne**
* long title: **Rust User Group Cologne**
* formal title: **The recurring Rust enthusiast's assembly near the fair city of Cologne, Germany**

---

The original issue text:

@Rustaceans/organizers-cologne
# issues

Our current name and url on meetup refer to Cologne and Bonn. The initial idea was to alternate meetups between Cologne and Bonn. But after 10 meetups we never actually had one in Bonn and it does not look this is really going to happen. And I think we have more guests from Aachen or Düsseldorf than Bonn.

=> **The reference to _Bonn_ does not make much sense.**

And these are all our current appearances on the web (EDIT: updated):
- meetup
  - url: **https://meetup.com/RustCologne** (old: https://meetup.com/Rust-Cologne-Bonn)
  - name: **Rust Cologne** (old: Rust Cologne/Bonn User Group)
- website:
  - url: **https://rust.cologne** (old: https://rustaceans.cologne)
  - subtitle: **Rust User Group in the area of Cologne/Bonn, Germany**
- github:
  - url: **https://github.com/Rustaceans/rust-cologne**
  - name: **Website for Rust User Group Cologne**
- twitter
  - url: **https://twitter.com/RustCologne**
  - name: **Rust Cologne**
- ccc-recordings:
  - url: **https://media.ccc.de/b/events/rustmcb**
  - tagged with: **Rust Meetup Cologne/Bonn**

=> **We managed to _always_ use something different**. :laughing:
# options
## 1) do nothing

everything as-is.
## 2) drop the reference to "Bonn" in our meetup group

this could look like:
- meetup group name: Rust Cologne (as Twitter)
- meetup url: meetup.com/RustCologne (as Twitter)
- everything else as-is.
## 3) streamline (almost) everything

this could look like:
- meetup as in (2)
- website url: rust.cologne
- github url: Rustaceans/RustCologne
- title either short "Rust Cologne" or long "Rust User Group Cologne" (maybe depending on the context)

-> everyhing as Twitter (except urls of video recordings).
# discussion

I know options (2) and (3) would break some URLs, which is not so nice. But we can do the following to mitigate this a little
- we can send one notification ahead of time to our mailing list + twitter that things will change. 
- plus one notification when the migration is completed
- we can choose a good timing (e.g. right _after_ a meetup and _before_ the next save-the-date?)
- I even volunteer to change URLs in some past announcements on users.rust-lang, rustplatz, rust calendar

btw: the alternative url in the last option is still available. But we will have to ask Harris Brakmic hosting who is hosting our website, if he would help us with this.

But first things first: What do you think?

**Comment by Florob** [comment]
Another data point is media.ccc.de which currently uses "Rust Meetup Cologne/Bonn", mostly because you can only fit so many letter on a preroll at a decent font size. The short name that is also reflected in the URL is "rustmcb".

I'm certainly in favour of harmonizing this a bit, but I think changing too much around causes more problems than it solves. In particular I would not change any of the URLs. There are bound to be places out of our control linking to them. The fact that URLs are rarely typed out these days, particularly beyond the domain, further sways me towards leaving them untouched.

I think consistently referring to the group as "Rust Cologne" is a good idea though. We could throw a "Meetup" or "User Group" in the middle for clarity, but personally I wouldn't.
The "Rust Cologne/Bonn User Group" title has always kind of bothered me. It just seems like the wrong order of words.

**Comment by colin-kiegel** [comment]
We would certainly break someones bookmark somewhere, but on the other hand we only had 10 meetups so far.

I'm more inclined to take this opportunity and also streamline the URLs, since this part is a "now or _never_" thing IMO. Plus rust.cologne is shorter and that may actually be something you type in your browser. :-)

PS: We could do the renaming in two steps. If we all agree on "Rust Cologne", we can change the title of the meetup group right away and continue the discussion about the URLs.

**Comment by colin-kiegel** [comment]
I included the ccc-recordings in the list and added this to my third suggestion
- title either short "Rust Cologne" or long "Rust User Group Cologne" (maybe depending on the context)

**Comment by xetra11** [comment]
What about Rust Northrhine Westfalia? Since as you said we had ppl. from Aachen, Dusseldorf etc. we mybe could widen the ring and nobody can ever complain about that :neckbeard:

**Comment by colin-kiegel** [comment]
@xetra11 I would make the name dependant on where we meet rather who is attending. Because there could be other meetups in this area in the future, if Rust gains more popularity. Maybe even in Aachen, Bonn and Düsseldorf. However it is likely that there will probably be only one Rust user group meeting in Cologne. Otherwise we might have to switch to Cologne-Ehrenfeld in the future. ;-)

**Comment by xetra11** [comment]
@colin-kiegel kk got your point 👍

**Comment by badboy** [comment]
:+1: on just Rust Cologne. Did someone secure the domain already? Otherwise I can take a look.
We wouldn't need to abandon rustaceans.cologne, but can certainly redirect everything.
That would probably not break too much. https://www.meetup.com/Rust-Cologne/ already works anyway.

**Comment by colin-kiegel** [comment]
I was thinking about securing the domain, but didn't yet, since I wanted to start the discussion first. Otherwise it would have looked like pushing this too much. I'm fine with securing the domain and redirecting stuff. This would allow an extended changeover period.

I wonder why this second meetup URL works. If we could make that redirect in the opposite direction, that would be much better however. :-)

**Comment by colin-kiegel** [comment]
Ok, I _really_ don't understand why this URL already works: https://www.meetup.com/Rust-Cologne/

But, the meetup [help article](http://www.meetup.com/de-DE/help/article/1664422/) about changing our meetup-URL says:
- Your old group web addresses will still work - they'll redirect members to your new address

So yes, we can easily migrate meetup. :tadaa:
And as @badboy suggested, we could redirect rustaceans.cologne to rust.cologne. However I would suggest we only do this for something like 12-18 months.

@killercup what do you think about all of this? If you agree too, I will change the meetup URL. The only question then is, which of these?
- https://www.meetup.com/RustCologne/ 
- https://www.meetup.com/Rust-Cologne/ 
- https://www.meetup.com/rust-cologne/ 

I have a tendency to streamline with our twitter presence, although RustCologne might not be as search engine friendly as Rust-Cologne - but I am no SEO-expert...

**Comment by colin-kiegel** [comment]
ah, ok ... on second thought I think I do understand why it works. Seems like this is not our first rename :bulb:

**Comment by colin-kiegel** [comment]
PS: the domain is only 50 ct/mth

**Comment by badboy** [comment]
where would you buy the domain?

**Comment by colin-kiegel** [comment]
https://hosting.1und1.de/domain-registrieren#stage actually 49 ct/mth, but
I didn't check the small print. It is possible this will be more expensive
after 12 months or something like that.

**Comment by killercup** [comment]
I'm okay with dropping 'Bonn' from the name.

> although RustCologne might not be as search engine friendly as Rust-Cologne

I would be surprised of that mattered.

> I'm more inclined to take this opportunity and also streamline the URLs, since this part is a "now or never" thing IMO. Plus rust.cologne is shorter and that may actually be something you type in your browser. :-)

But I _just_ managed to commit 'rustacean' to my fingers' muscle memory… 😉 No, really, `rust.cologne` is much nicer to type. 1und1 wants 49¢/month in the first and 99¢/month from the second year on. I usually buy domains from inwx who want 9,90€/year.

Redirecting the domains needs to happen at the current DNS provider (cc @brakmic), either by using a redirect feature they provide, or by pointing the domain record to a server we set up (i.e. a virtual host that just returns nice 301s).

**Comment by badboy** [comment]
I have enough servers to do so.

**Comment by brakmic** [comment]
No problem. Whatever you guys want to have. Just let me know what should be done.

**Comment by brakmic** [comment]
One additional idea: I could simply buy rust.cologne as an additional domain to the rustaceans.cologne. Then I'd leave "rustaceans.cologne" to expire in July 2017 and from then on we'd simply continue with rust.cologne only.

Don't know what you're currently doing so I don't want to click on "take this domain"-button. 

It should be a group-based decision.

Regards,

**Comment by badboy** [comment]
I would not let it expire so soon (yadayada internet links all around). If cost is a problem I'd be happy to cover it for at least another 1-2 years.

**Comment by brakmic** [comment]
Money's always the greatest of all problems. That's what makes the world tick and body count rise. 
Of course, I could leave ""rustaceans.cologne" to live for another year (unless I decide in 2017 to leave you all and join a C++ group).

So, what about "rust.cologne"?

**Comment by colin-kiegel** [comment]
Thx Harris, that would be great!

I'll Cover your Drinks at the next meetup. 😁🍹

**Comment by brakmic** [comment]
Thanks @colin-kiegel 

I hope I'll be there, next Wednesday. 🍺 

Just added "rust.cologne" to the domain list. Will take a few minutes until it gets activated. 
Then I'll update the DNS providers and rust.cologne will become aliiiive! 👽

**Comment by brakmic** [comment]
The new URL is live.

I allowed myself to change a few configs (yaml) and templates because this is a nice excuse to produce some errors in future. 😁 

The old URL now redirects to [rust.cologne](rust.cologne)

I'm offline now. Good night.

**Comment by colin-kiegel** [comment]
ok, thanks everyone. I have updated meetup - our primary URL now is: 
- http://www.meetup.com/RustCologne/
  And the user group is now only called "Rust Cologne" and it links to rust.cologne. I think we still have to update some links here and there (e.g. our website and maybe youtube/forum links), but we can do this on the way.

I already updated the link on twitter and changed the description there to "Rust User Group Cologne".

I already like everything much better. As a rule of thumb and according to our discussion here, we should try to stick to these now, whenever possible, right?
- part of URLs: **RustCologne**
- short title: **Rust Cologne**
- long title: **Rust User Group Cologne**

**Comment by killercup** [comment]
Wow, that was quick! Thank you @brakmic! Redirect works, and I just added the domain to the Google Maps API key (#13).

@colin-kiegel, looks good. May I suggest that we also add

> - formal title: **The recurring Rust enthusiast's assembly near the fair city of Cologne, Germany**

😉 

Alternatively I think it's fine to write `rust.cologne` instead of `RustCologne`.

**Comment by badboy** [comment]
Btw, `rust cologne` already googles quite good. However, we might want to mention "Rust Köln" a bit more (just to get above "Rüst (Stolberg, Rheinland)" and "Europapark Rust")

**Comment by killercup** [comment]
Feel free to buy `rust.koeln` :)

**Comment by killercup** [comment]
Anything else we need to do/decide here, @colin-kiegel?

**Comment by colin-kiegel** [comment]
@killercup 
- I like the formal title, very creative. ;-)
- rust.cologne would not work with meetup (only letters, numbers, and dashes allowed) - but otherwise a good suggestion :-)
- I just replaced the URLs on rust.cologne and updated the title and added your "formal title" as new description
- I am quite happy with the state we have now, so IMO we can close this now.

Thanks everyone. :+1:

**Comment by colin-kiegel** [comment]
PS: feel free to reopen if you see any need for further discussion!
