### ISSUE TITLE
Other video uploads

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#12]
Someone uploaded our recordings to YouTube: https://www.youtube.com/channel/UCv8EHZ7_Ti9ls5hLR5knibw

Are we okay with that?

(via https://www.reddit.com/r/rust/comments/54dn2f/rusts_meetings_collection/)

**Comment by killercup** [comment]
I just saw that as well but didn't want to write a comment on mobile. What
license did we choose for those videos (if any)?

I'm personally fine with them being uploaded to YouTube, but it should be
to a somewhat official channel (like the new rust videos channel for
conference videos).

Jan-Erik Rediger notifications@github.com schrieb am So. 25. Sep. 2016 um
10:10:

**Comment by badboy** [comment]
We did not add any license.
I am okay with YouTube as well personally. I do have access to the (official) Rust Video channel, so I could re-upload them there.
I don't know of a way to contact a YouTube user other than report them or one of the videos. Maybe the Reddit submitter is the uploader?

**Comment by colin-kiegel** [comment]
I think we have not picked a license. What about some creative commons?

Pascal Hertleif notifications@github.com schrieb am So., 25. Sep. 2016,
10:13:

**Comment by killercup** [comment]
We should discuss any possible license with the people who actually gave
the talks. (I could imagine that while they might be okay with 'share
alike', they'd want 'no modifications').

Colin Kiegel notifications@github.com schrieb am So. 25. Sep. 2016 um
10:29:

**Comment by killercup** [comment]
> I don't know of a way to contact a YouTube user other than report them or one of the videos.

Just write a comment on one of the videos, @badboy? :)

BTW, what bothers me just as much as uploading some already-free-and-public videos is that the uploads are in 480p only… 😅

**Comment by Florob** [comment]
The outro of the videos specifies CC-BY. In general I think YouTube uploads are fine, and also permitted by the license as currently stated. The fact that the uploads are set to "YouTube Standard License" bothers me though.
Are we sure the uploads are 480p only, and not just still in YouTube's encoding queue? That seems more plausible to me.

**Comment by killercup** [comment]
> The outro of the videos specifies CC-BY.

Oh, that is very good to know. I've never noticed that before.

> Are we sure the uploads are 480p only, and not just still in YouTube's encoding queue?

The videos were uploaded 22 hours ago. Does YouTube usually take that long?

**Comment by Florob** [comment]
> The videos were uploaded 22 hours ago. Does YouTube usually take that long?

I admittedly lack experience. From what I know they prioritize by channel/video popularity to some extent. Also, high quality formats sometimes seem take significantly longer. So I wouldn't rule it out, but it's not unlikely that it was re-encoded so it wouldn't take ages to upload I guess.

**Comment by colin-kiegel** [comment]
I am quite sure that no harm was intended. Maybe someone was just worried, that the videos might disappear from the ccc-website someday.

But still, I would suggest we politely ask him/her to change the license via a comment. And if he/she does not comply to fix the license and add the attribution within a couple of days, @badboy could use the action "report > infringes my rights" on the webasm-video. And we could ask some other people to do the same on their recordings. I am sure the youtube team will respond positively to the reports, since the original cc-by outro is still contained in the youtube videos.

PS: Youtube has an [option](https://support.google.com/youtube/answer/2797468?hl=en) for CC-BY

**Comment by badboy** [comment]
Comment sent. Will follow up

**Comment by badboy** [comment]
There we go: https://www.youtube.com/watch?v=bvJCMhJ3RnQ&list=PL85XCvVPmGQjMUncbxYjzS60zUSWoITrx

**Comment by badboy** [comment]
Uploaded all of our videos into a playlist of the Rust Videos account. Closing this.

**Comment by killercup** [comment]
Do you want to add the Youtube links to the website?

**Comment by colin-kiegel** [comment]
If we link the youtube videos, they might get more views and higher ranking.

@Florob: Do you think it makes sense to host _new videos_ on youtube _and_ c4 or only youtube?

**Comment by Florob** [comment]
To me part of this is definitely ideological. We (as in people at the C4) build media.ccc.de to have a data retention free non-user tracking platform. I would tend to publishing on both, YouTube mostly for visibility.
It might make sense for me to up the ante on the media.ccc.de side a bit. Currently I only upload HD video there, the backend additionally allows for SD and audio.

**Comment by badboy** [comment]
I think publishing on both is good.
