### ISSUE TITLE
Need new Google Maps API key

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#13]
with the changed domain we need a new key.

**Comment by killercup** [comment]
That key is associated with my Google account. I just added `rust.cologne` to the domains it can be used on.

**Comment by badboy** [comment]
:+1: I have no idea how anything associated with a google account works ¯_(ツ)_/¯

**Comment by colin-kiegel** [comment]
could you please add my localhost? .. just kidding ^^

**Comment by killercup** [comment]
You kid, but I already added it to develop the site locally! 😂

![bildschirmfoto 2016-09-30 um 18 10 05](https://cloud.githubusercontent.com/assets/20063/18998504/3671b6b2-8739-11e6-853e-f6f3bdcd1012.png)
