### ISSUE TITLE
Glühwein Meetup in December

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#16]
@Rustaceans/organizers-cologne Do we want to have a meetup in december? I am a bit sceptical, due to two reasons:
- we are already offering a lot of activities in mid november, which is also later than usual, i.e. closer to december
- december is a very busy time for most people
- I would rather not advertise more than two future meetups simultaneously. IMO we should not start advertising a new meetup before Rust/Audio. 

I am thinking about letting our users decide and send out a poll
* what week should our next meetup be? (multiple choice: December - January)
* which days generally work good for you? (mc)
* what would you like to do at our next meetup? (text)
* would you like to give a presentation about something? (text)

todos:
- [x] Settle for a date: **2016-12-07**
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
  - No agenda
- [x] Final invitation (deadline **2016-11-30**)
  - [x] meetup: http://www.meetup.com/RustCologne/events/235656237//
  - [x] website: http://rust.cologne/2016/12/07/christmas-maket.html
  - [x] twitter: https://twitter.com/RustCologne/status/803324886206836737
  - [ ] community calendar
  - [x] reddit: https://www.reddit.com/r/rust/comments/5fp2tv/impl_glühwein_for_rustcologne/
  - [ ] rust-lang forum: 
  - [ ] rustplatz: 

# Invitation draft

<https://github.com/Rustaceans/rust-cologne/issues/16#issuecomment-263311055>

# Rust News
- ...

**Comment by colin-kiegel** [comment]
Obviously I can't count ... two reasons, three bullets. ;-)

**Comment by killercup** [comment]
Thanks for bringing this up, @colin-kiegel!

The next two 'regular' dates are **December 7th** and **January 4th**.

I can see why that might conflict with Christmas stuff and vacations. Personally, I don't have anything planned for either of those Wednesdays and would show up even if just to make/drink Glühwein.

> I would rather not advertise more than two future meetups simultaneously. IMO we should not start advertising a new meetup before Rust/Audio.

Why? To not confuse people? IMHO being able to offer dates ≥3 weeks ahead of time is worth more to our members than having to decipher lists with > 1 event[^1].

Maybe we can ask people about what they prefer? (Which brings me to…)

> I am thinking about letting our users decide and send out a poll

I think involving more members in our decision making is a _great_ idea. The Open Space meetup was really nice, and I have high hopes for the audio meetup as well – both largely _not_ driven by us organizers.

I'm not sure if a poll (as in: doodle or Google Forms) is the best way to go, though. While it helps getting some empirical data, our data set will likely be quite small and a lot of detail goes missing. I'd just point people to this Github Issue (and it's successors for future meetups); and maybe ask a few direct question in the issue text.

- - -

[^1]: By the way, to include the novemb.rs event as well as the audio meetup, I recently upgraded our website to be able to list ≥ 1 future events. Just have a look at how it's currently displayed. I'm looking forward to your feedback :)

**Comment by colin-kiegel** [comment]
@killercup 
Regarding the timing of emails: Every email we write comes with "unsubcribe from this mailinglist". Currently 166 from 168 members are on our mailing list, I just don't want to loose anyone. That is why I don't want to send out too many emails in short order. On the other hand you might say, that we haven't seen 168 people at our meetup so far and we probably wouldn't loose the people showing up regularly. I don't clutch to my idea of waiting until after the Rust Audio meetup.. I'm fine if you, or any other organizer wants to go ahead quicker than that. ;-)

I'm also fine with pointing people to this thread, which might give a better quality of feedback but probably less quantity, since it takes more time to join a discussion than answering a brief poll IMO.

Would you like to write such an email?

**Comment by killercup** [comment]
We talked a bit this at novemb.rs and the consensus was something like this: No full-blown meetup in December, instead let's do something that involves glühwein.

One idea was to meet at a not-that-overcrowded christmas market, another was to make glühwein at the c4.

FTR, another topic was to whether we wanted to join the Ruby meetup in January (see #19).

**Comment by badboy** [comment]
I want/need to write something up anyway, so we could quickly collect a few of the things we did/talked about:

- Some audio/midi processing
- Flif decoder by @panicbit & @killercup 
- OpenSSL buffering by @Florob 
- Builder/Setters/Getters by @colin-kiegel 
- rustaceans.org by @badboy
- @colin-kiegel helped @sangyye get started with Rust

**Comment by colin-kiegel** [comment]
I think a minimalistic glühwein meetup is a good compromise for december.

But I will probably drop out this time, since neither alcohol nor sweet stuff are my kind of thing.

=> Anyone interested in sending out some invitations this time, please step up. ;-)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne Do you know which christmas market you want to go to? And where you want to meet? Please consider that people might be late - i.e. you may want to send a phone number to everyone who RSPVd on meetup.

Speaking of which, I just want to remind you, that we have *not* announced any meetup for december yet. We haven't even send a save-the-date. Since I'm opting out this time I'd prefer to leave that to you - that is if you still want to go to the christmas market.

**Comment by colin-kiegel** [comment]
PS: https://www.meetup.com/de-DE/RustCologne/events/235656237

**Comment by badboy** [comment]
Sorry, @colin-kiegel. We will get this going. Thanks for your reminder and effort.

**Comment by killercup** [comment]
Any suggestions for which Christmas market to go to? I can whip up an
invite text tonight so we can let people know over the weekend.

Jan-Erik Rediger <notifications@github.com> schrieb am Fr. 25. Nov. 2016 um
10:17:

**Comment by killercup** [comment]
@Florob, you mentioned there was a quieter christmas market somewhere on Venloerstr, right? Did you mean [Weihnachtsmarkt im Stadtgarten](http://www.weihnachtsmarkt-stadtgarten.de) ([map](https://www.google.de/maps/place/Weihnachtsmarkt+im+Stadtgarten/@50.9429322,6.9353748,15z/data=!4m2!3m1!1s0x0:0x400ce56f98bcd217?sa=X&ved=0ahUKEwjMqtrs4svQAhXI1ywKHW5cBg8Q_BIIczAK))?

I propose we just set a location and send out an invite asap.

My suggestion for an invite text (full of assumptions; please tell me what to change):

> Dear Rustaceans,
> 
> The year is coming to an end, and it is time to announce our last meetup for 2016. Actually, no, scratch that: "Last meetup" sounds so… final and not like the grand conclusion of an awesome year full of exciting Rust-related stuff! Let's instead do something hopeful, advent-y, and surprisingly traditional: An evening at the christmas market. Think of it as `impl Glühwein for RustCologne` (actually part of a generic impl that also includes other holiday-y beverages like hot cocoa).
> 
> We invite you all to join us for a casual evening at Cologne's Weihnachtsmarkt im Stadtgarten. We'll meet at around 7pm next Wednesday, December 7th, 2016, at the entrance at Venloer Straße (2min from Bahnhof West/Hans-Böckler-Platz, you can find a map [here][1]), and head in together. The christmas market closes at 21:30, but we're open to go to a pub or somewhere else afterwards.
> 
> Whether you come for hot punch, Rust, non-alcoholic beverages, cheesy christmas presents, good company, or Currywurst – we're looking forward to seeing you there!
> 
> Yours,
> 
> Jan-Erik, Pascal, Florian, and Colin
> 
> PS: If you're running late or need help with directions, feel free to email/tweet us/one of the organizers, we'll answer as quickly as possible, or give you a call if you prefer.
> 
> [1]: http://www.weihnachtsmarkt-stadtgarten.de/index.php?id=11

**Comment by Florob** [comment]
@killercup That is the one I was thinking of. No guarantees on the  crowdedness though. It was okay the one time I was there last year.

**Comment by badboy** [comment]
Maybe just a little note about non-alcoholic beverages? (Can we say Punsch? or non-alcoholic Punsch?)
I just want to make sure we're not forcing to drink here.

**Comment by killercup** [comment]
@badboy of course! Good point. I kept the `impl Glühwein`, but added

> (actually part of a generic impl that also includes other holiday-y beverages like hot cocoa)

and later on:

> […] hot punch, Rust, non-alcoholic beverages, cheesy christmas presents, good company, or Currywurst […]

**Comment by colin-kiegel** [comment]
invitation sounds good! 👍

**Comment by badboy** [comment]
@killercup I like that!

**Comment by killercup** [comment]
Awesome! I'll send out the invite then!

**Comment by killercup** [comment]
@colin-kiegel, I just announced the meetup. This results in an email to all members, doesn't it? Otherwise I'll send an email via meetup.com as well.

*Edit:* Promoted event on website and twitter.

**Comment by colin-kiegel** [comment]
@killercup Yes, that sends the invite and I can confirm I received it. However that can only be done once per event. This is why I usually send our final / second invitation via the mailing list which looks different (in case any of you wondered). ^^

**Comment by killercup** [comment]
Cool! It only contains a truncated version of the invite text, so I'm thinking about sending a mailing list mail Wednesday morning, which includes the invite again but also mentions the ongoing discussion about the January meetup. Is that alright with you guys?

**Comment by colin-kiegel** [comment]
Sure. I think two invites per meetup is still ok. Regarding the January meetup I would rather send the regular (save-the-date) invitation as quickly as possible after the Glühwein meetup, since I believe hitting the publish button on meetup might trigger additional magic like inclusion in public meetup listings etc. Therefore I would try to avoid to much redundance with that in the next Glühwein invitation. But that's just my two cents. Feel free to do as you like. :-)
