### ISSUE TITLE
Rust meets Ruby

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#19]
@Rustaceans/organizers-cologne What do you think about a joint meetup with the [Cologny Ruby User Group](http://cologne.onruby.de/)? @sangyye suggested to join both meetups. A possible date would be Wednesday 2017-01-18. The Ruby User Group has a web-focus (ruby on rails) and a possible cross-section could be creating rust plugins for ruby applications. The ruby meetup seems to be of comparable size to our, e.g. 10-20 participants per meetup. They have alternating locations at sponsoring companies and could perhaps organize a location which could hold 20-40 participants.

todos:
- [x] Basic Agenda, i.e. are we going to join our meetup?
- [x] Settle for a date: **2017-01-18**?
- [x] Find a location (for both meetups): 
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Final invitation (deadline **2017-01-08**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/235877954/)
  - [x] [website](http://rust.cologne/2017/01/18/ruby-meets-rust.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/818126572456644608)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=aG4wMjZlcHViZjFuNWJrcnBxa3I0Z2g2cDAgYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/5mrkyf/meetup_in_cologne_on_20170118_in_cooperation_with/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-15-ruby-meets-rust/8802)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-15-ruby-trifft-rust/189)

# Invitation draft

```markdown
Title: CGN #15: Ruby meets Rust

We are pleased to announce another cooperative meetup, this time with the folks of Cologne.rb, the local Ruby user group.

So join us on the third Wednesday in January 2017 at Railslove (Coworking Cologne) for an evening of everything that starts with "Ru"!

Agenda
* Rust and Ruby - make it fast (by @badboy)
* Open Discussion, Drinks, Socializing, ...

**[You can register here](https://www.meetup.com/RustCologne/events/235877954/)** - please note the different location!

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin
―  
This meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.
```
# Rust News
- [rust 1.14 (2016-12-22)](https://github.com/rust-lang/rust/blob/stable/RELEASES.md)
-- ...
- recent crates of the week
-- [cargo benchcmp](https://github.com/BurntSushi/cargo-benchcmp): A small utility for comparing micro-benchmarks produced by cargo bench

**Comment by killercup** [comment]
A short recap of the points we brought up at novemb.rs:
- Our usual date in Januar is 2017-01-04 which is pretty early in the year
  (not that many people might show up). The ruby meetup's date is nicer.
- we expect that many people sho show up only know one of the two languages.
- A common topic concerning rust and ruby is speeding up ruby by replacing
  ruby modules with ones implemented in rust that have the same API (maybe
  using helix or ruru). @badboy said he'd be willing to talk about that.
- I mentioned that it might be interesting to talk about software
  architecture, i.e. the differences in how you structure your code and
  design your apis and rust vs. ruby. This probably requires knowledge in
  both languages.

Colin Kiegel notifications@github.com schrieb am Sa. 19. Nov. 2016 um
14:28:

**Comment by colin-kiegel** [comment]
I've updated the date of our January save-the-date to 2017-01-18
https://www.meetup.com/RustCologne/events/235877954/

PS: This is however not yet send out - only a stub visible to people visiting our meetup page.

**Comment by Florob** [comment]
Is the general assumption that the Ruby meetup will be providing the room?

**Comment by colin-kiegel** [comment]
@Florob good point about the room.

I expect the C4 will not be available for us on that date, due to the Open Source Audio Meetup (@Florob: is that correct?). And even the main C4 room was available, it might be a bit crowded if a lot of people show up from both Rust + Ruby meetups.

On the other hand @sangyye told me that the ruby meetup organizes alternating rooms anyway and should be capable of organizing a big enough room on that date.

In that sense my line of thinking was:
(a) either the joint meetup in January works out and we go with a room from the Ruby meetup
(b) or we postpone the joint meetup and pick a new date in January (where we can use the C4 again as usual)

PS: I've removed the location from the save-the-date entry.

EDIT: Fat-fingered the save button too early. ^^

**Comment by colin-kiegel** [comment]
@sangyye @Rustaceans/organizers-cologne most important question is: Are we ready to settle the question whether we want to join the meetup in January already?

@sangyye
* until when could you settle the question about the room?
* Do you know of anyone who wants to talk about Rust+Ruby? Or maybe a very brief presentations about possible use cases?
* Are there any public discussions from your user group about this idea, which links or summary you could post here?

@killercup are you actually _volunteering_ for a second talk - or was that only you thinking out loud theoretically about the possibility of giving a talk? (I am not sure). ^^

General questions
* Would we feel comfortable doing the joint meetup with only one general talk (e.g. from badboy) + following discussion, or do we want to have at least one other topic/presentation/etc.?

**Comment by axelvonleitner** [comment]
Hey guys, 

we're still waiting to see if the C4 would be available on that date, but if you already know it's not we should start to look for alternatives. Generally what I've seen, our group would be interested in a joint meetup, however we should try to avoid rescheduling and stick with the 18th. 

I think the room should be large enough for at least 20-25, maybe 30 people then. I'm afraid that only a small number of the ruby group will be interested in the Ruby/Rust meetup, especially since we were having little visitors within the last meetups anyway. So I guess we don't need that much of space. 

For that size we would have some options at hand. If we agree on the date and the joint meetup I could try to fix some of the options and let you know. 

Regarding content / talks, I haven't heard of somebody who has something at hand or in mind. From our site one general talk and a following discussions would be fine. For many of the Ruby guys this will be pretty new so probably some questions arise.

**Comment by killercup** [comment]
Oh, so this is happening? Cool!

> @killercup are you actually volunteering for a second talk - or was that only you thinking out loud theoretically about the possibility of giving a talk? (I am not sure). ^^


@colin-kiegel, this was me thinking out loud about what talk I'd want to hear. If for that to happen I need to be the one giving it… well, I can live with that :)

My main concern was not me giving a talk, though, but if anyone would actually be interested in a talk about the differences and similarities in how one can structure code and APIs in Rust and Ruby. It assumes familiarity with both languages and might be very abstract, so not exactly newcomer friendly… It can be stretched a bit to see Ruby as a representative of (a certain kind of) OOP languages though.

By the way, is the Ruby meetup in German or English?

PS: I'll ask a few coworkers from Bonn if they want to come.

**Comment by axelvonleitner** [comment]
The Ruby Meetup is in German most of the times, but when there are people only speaking English or the talk is in English that is fine to most of the guys ;-)

**Comment by Florob** [comment]
@axelvonleitner, @colin-kiegel:
I would not want to say that the C4 is unavailable per se, but I'd rather view it as a last resort.
There is already another meetup at the C4 on that date. They usually use our smaller room, but I'd not be too happy restricting them to it.
The larger room is also at capacity at ~20 people, unless we shift tables around and seat people in rows.

**Comment by badboy** [comment]
So I'd definitely be interested in a joint meetup with the Ruby folks. I could even prepare a talk on how Rust can be used to extend Ruby and make it faster, if there is interest in that.
This can be a starting point for the discussion. Of course @killercup's more general approach of code structure in either language works just as well for a discussion.

**Comment by axelvonleitner** [comment]
topic sounds great @badboy 

I'll then talk to some folks regarding the location. Anybody thinks we'll be > 30 people?

**Comment by killercup** [comment]
@axelvonleitner I don't know how many people usually attend your events, but based on other meetups I'd be surprised if ≥30 people show up.

If this is at 'your' location: How do you handle sign ups (if you do that at all)? At our last events signing up was totally optional.

**Comment by killercup** [comment]
FYI @badboy, just saw that wycats will be giving a talk about helix at the SF meetup in December: <https://www.meetup.com/Rust-Bay-Area/events/235285192/>.

**Comment by colin-kiegel** [comment]
@axelvonleitner Cool, please let us know as soon as a location is confirmed. We will then send out early save-the-date invitations to our user group. :-)

**Comment by axelvonleitner** [comment]
Hey guys, 

we agreed on [Railslove](https://www.google.de/maps/place/Railslove+GmbH/@50.9222161,6.9606642,17z/data=!3m1!4b1!4m5!3m4!1s0x47bf259d7fc841a5:0x57dc77027e0e7eb9!8m2!3d50.9222161!4d6.9628529) as location for the RUST/Ruby Meetup in January. We organize signups via our events page, so feel free to join there: http://www.colognerb.de/events/januar-meetup-2017

So far I only added the topic of badboy but will add the other one that you guys thought of as soon as I see a topic. 

Final question: The talk/s will be in english or german? I would add that to the event site then. 

Cheers!

**Comment by colin-kiegel** [comment]
@axelvonleitner cool, thx.

**Language of talk and discussion**:
Our user groups is used to alternating languages of our meetups - and it should be all good as long as we give a clear hint in the announcement.

Depending on context we had basically three variations of announcement by-lines:
a) Important Note: This meetup will be in German.
b) Important Note: This meetup will be in English.
c) This meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.

Most of the times we pick (c) and would ask the presenters if they are also ok with that. As a result I would say that roughly half of our meetups have been English so far including introduction, talks and group discussion. And roughly half of our meetups have been German.

* How does your user group handle language choice so far?
* Is there a clear preference for one language?

**joining the event**:
We use meetup to communicate our events and offering registration of participation (RSVP). Most of our users have a meetup account and most of them also RSVP in advance - but not all of them and we don't enforce it by any means.

I would like if we could have this event on both of our websites, _including_ registration. We can set a limit on our registration form (our standard limit is 20, which we never hit in the past). This way people could choose how to register (via meetup account on our website, or github account on your website).

I mentioned, that we usually treat RSVPing as optional. If you have concerns about running out of space with too many people coming without being registered, I could imagine another by-line to our announcement, like that we may check the RSVP-status this time, _if_ we are running out of space.

Sorry for the long post - I hope this gives you some context about our meetup customs. ;-)

**Comment by colin-kiegel** [comment]
PS: Historical fun fact: Our [very very first Rust meetup](https://www.meetup.com/RustCologne/photos/26300362/?_locale=de-DE#440340076) was at Railslove on 2015-07-29 (8 people back then). *sentimental sigh* ^^

**Comment by badboy** [comment]
\o/ - When should we send the invitations? By the end of this week?

**Comment by killercup** [comment]
Oh, we have all the details already it seems! Let me add it to rust.cologne real quick. As far as I'm concerned, we can announce this right now!

How should we tell people to RSVP? Meetup, colognerb.de, both, neither?

colognerb.de has this feature but I don't like the UX: Clicking on "Teilnehmen" tells me to log in; log in is hidden behind the navigation menu; signup via Twitter and Github is possible and worked for me; I tried Twitter first, saw it wanted access to unrelated stuff, and switched to Github, where it only wanted access to public information to identify me, which sounded better. I can easily see people being put off by that.

@badboy, how long to you think your talk is going to be? Do you maybe want to do a hands-on afterwards? If there is a demand for a second talk, I'm sure I could to an "Understanding Rust with lots of analogies to Ruby" (think "You know {Struct.new, ActiveRecords's enum, mixins/concerns, …}, let me tell you about {struct, enum, traits, …}").

**Comment by badboy** [comment]
I would go for the usual 20-30minute talk.

**Comment by colin-kiegel** [comment]
@sangyye @axelvonleitner We are about to sending our save-the-date information. I already opened the RSVP on our meetup page and set the limit to 16 instead of our usual 20. :-)

Should we announce this meetup to be German, English or spontaneously-decided? Whats your standard there?

See this comment for more details: https://github.com/Rustaceans/rust-cologne/issues/19#issuecomment-264709120

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne since we basically agreed on the text I will probably send the save-the-date information tomorrow morning. https://www.meetup.com/de-DE/RustCologne/events/235877954/ :-)

**Comment by colin-kiegel** [comment]
@killercup I think a second talk featuring the similarities of both languages would be an interesting addition. :+1:

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne I would like to send our final invitation roughly next weekend to remind our user group about this meetup. Please let me know if you want to change something about the [current invitation text](https://github.com/Rustaceans/rust-cologne/issues/19#issue-190496447), which we already used for the save-the-date announcement. If not, I will just use the same text again. :-)

**Comment by colin-kiegel** [comment]
PS: happy new year :tada: :fireworks:

**Comment by badboy** [comment]
Happy New Year! :tada: :fireworks: – I'm fine with the text, maybe extend it with a new year greeting?

**Comment by killercup** [comment]
Happy new year! The invite text is fine, but I agree we should add a New
Years greeting :)

Hm, maybe one thing we should decide beforehand is this: What are our goals
with this meetup? Tell people that rust is awesome, show people how awesome
rust is, or actually teach people how to write rust? Don't want to be
confused and not get anything out of the meetup. Depending on that we might
want to do a short introduction to Rust -- as well as for ruby.

@badboy, how did you plan on giving your talk? Open an editor and a
terminal and show people how to add native rust code as a dependency in
their gem? This might be a way of introducing one or both languages, but
could easily turn into an unmanageable live coding session…

If you want to do that at all, I'd be willing to help out. Maybe take turns
doing pair programming with an audience? (Which does not sound like
preprogrammed chaos at all! :D)

(Btw: I [wrote down][1] a few notes regarding Rust and Ruby over the
holidays because I couldn't help myself.)

[1]: https://scribbles.pascalhertleif.de/rust-and-ruby.html


Jan-Erik Rediger <notifications@github.com> schrieb am So. 1. Jan. 2017 um
23:47:

**Comment by badboy** [comment]
I did not yet decide on any format. I guess I will definitely first give a look at what Rust can offer to Rubyist and than show the current status of integrations possible.

**Comment by colin-kiegel** [comment]
ok, I did the missing final announcements except reddit. Anyone willing to do this?

**Comment by colin-kiegel** [comment]
Oh, I was just about to ask about the language preference and realized that @axelvonleitner basically [answered it already](https://github.com/Rustaceans/rust-cologne/issues/19#issuecomment-263297415). I missed that before! ^^

I will update the forum posts and meetup to include "This meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.".

PS: On the morning of 2017-01-18 I will send a reminder to anyone who rsvpd to hint about the different location this time.

**Comment by killercup** [comment]
Thanks, @colin-kiegel! (Posted to reddit.)

**Comment by colin-kiegel** [comment]
@killercup I haven't mentioned your talk, since you still seemed a bit undecided. However you could still do it spontaneously / unannounced IMO. ;-)

**Comment by killercup** [comment]
I'm totally up for discussing this ad hoc and in-depth for as long as someone is willing to talk to me! (So, basically just like regexes, diesel, session types, and all my other favorite subjects :D)

**Comment by colin-kiegel** [comment]
I'll probably be a bit late today due to piano lessons until 19:00. Just start without me. ;-)

**Comment by killercup** [comment]
No worries, Colin. I'll try to be there at around 18:40, but can't promise anything. And thank you for the reminder mail we just got via Meetup :)

**Comment by killercup** [comment]
Great meetup last night! I really enjoyed it and was stunned how many people turned up! Did someone count? I guess there were at least 25 people.

I was pretty surprised at how diverse and all-around interesting the picks in the introduction round were. Sadly, I don't think someone wrote them all down, and I didn't keep track of all that seemed interested.

Also, I think it'd be interesting to ~~steal~~ adopt the idea of a series of "~~Ruby~~ Rust is magic" talks. Though one could argue that our proc macro event is just that! 😄 (Other than the, presenting `Cow`, `Into`, or any of [these](https://scribbles.pascalhertleif.de/hidden-treasures-of-the-rust-ecosystems.html) might also be interesting).
