### ISSUE TITLE
imprint

### ISSUE THREAD

**Issue by brakmic** [Rustaceans/rust-cologne#2]
Das Impressum sollte, m.E.n. angepasst werden.

Weil mehrere Leute per GitHub modifizierend zugreifen können, kann ich nicht als einzige Kontaktperson da stehen. 

Gibt es da eine Regelung für Meetups?

**Comment by killercup** [comment]
Oh, guter Punkt. Hatte das damals von der Domain übernommen. Ich weiß
nicht, ob es da eine Regelung gibt, aber ich gucke mal was man da machen
kann.

Harris Brakmic notifications@github.com schrieb am Mi., 3. Feb. 2016 um
23:20:

**Comment by killercup** [comment]
Hab's mal auf mich geändert, da ich eh bis jetzt alle Inhalte eingepflegt habe.
