### ISSUE TITLE
February Meetup: Macros 1.1

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#22]
Todo:
- [x] Settle for a date: **2017-02-01**?
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Final invitation (deadline **2017-01-17**)
  - [x] [meetup](https://www.meetup.com/RustCologne/events/236858848/)
  - [x] [website](http://rust.cologne/2017/02/01/proc-macros.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/822052310616522752)
  - [x] [community calendar](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=YWw1MmxtOTk1aXZnbm5pNmU4bzRyZW4xcTggYXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZw&tmsrc=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/5p385d/celebrating_proc_macross_eve_rust_cologne_meetup/)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/hacking-macros-1-1-cologne-meetup-2017-02-01/9006)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-16-macros-1-1/192)
- [x] Prepare "Introduction to Macros 1.1" slides/examples

# Invitation draft

```markdown
Title: Hacking Macros 1.1 (Cologne / 2017-02-01)

Let's get together and hack on some brand new Rust macros, shall we? :-)

Join us on 2017-02-01, 19:15 CET in Cologne, Germany.

With Rust 1.15 scheduled for early February, the highly anticipated procedural
macros 1.1 (aka custom derives) are finally going to be stable.

Agenda

* A short introduction to macros 1.1
* Peer up (optional)
* Pick a project and start hacking(*)

(*) If you are unfamiliar with Rust itself or procedural macros in Rust, you
are welcome to start with a small toy project, work in a group, and ask fellow
Rustaceans for guidance!

As always, you can enjoy some drinks, meet nice people and discuss about Rust.

**[You can register here](https://www.meetup.com/RustCologne/events/236858848/)**.

We are looking forward to seeing you. :-)

Yours,
Jan-Erik, Pascal, Florian and Colin

—

The meetup will likely be held in German, we will however reevaluate this at the beginning
of the evening and may switch to English if needed.
```

# Rust News

- [Rust Language Server Alpha Release 2017-01-25](https://internals.rust-lang.org/t/announcing-rust-language-server-alpha-release/4621)
- [Procedural Macro Attributes on Nightly Rust](https://github.com/rust-lang/rust/pull/38842)
- [crates.io: Categories and CI badges](http://www.integer32.com/2017/01/20/categories-and-ci-badges.html)
- [1.15 release notes](https://github.com/rust-lang/rust/pull/38966)

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne February is coming fast and we already got RSVPs for our 'regular' meetup on Februar the first: https://www.meetup.com/RustCologne/events/236858848/
- Any suggestions what we can do?
- Shall we try open space again?

**Comment by killercup** [comment]
Thanks for the reminder @colin-kiegel!

According to <http://rusty-dash.com>,

> Rust 1.15 stable will release on Fri Feb 03 2017.

…which is _just_ after our regular date on February 1. Oh, and 1.15 is the _highly_ anticipated release that stabilizes macros 1.1, i.e. custom derive! Which means we can _finally_ use serde and diesel on stable!

So: How about an evening of hacking on crates using macros 1.1? I don't know about you, @Florob, but I have seen both @colin-kiegel and @badboy fiddle with proc macros over at <https://github.com/colin-kiegel/rust-derive-builder/pull/28>, so I guess we as organizers can mentor people unfamiliar with this if needed.

By the way, given that most rust stable builds were done a few days ahead of the scheduled date, there is a good chance we get to play with the actual 1.15 release! Otherwise, the beta shouldn't differ from the stable release much.

Suggestions for projects to work on:

- The already linked to derive-builder: ~~https://github.com/colin-kiegel/rust-derive-builder/pull/28~~ **Update:** colin-kiegel/rust-derive-builder#32
- Diesel, but the proc macros require a lot of knowledge of the codebase
- One of [these fine crates](https://crates.io/crates/syn/reverse_dependencies), e.g. [validator](https://github.com/Keats/validator)
- any other project `p` that could benefit from a `p_derive` crate!
- help extend the crates used for writing proc macros more comfortably (syn, quote, et.al.), e.g. dtolnay/syn#25

**Comment by colin-kiegel** [comment]
ingenious, I like it :-)

**Comment by killercup** [comment]
By the way, setting the invite deadline to two weeks before the event will coincide with our meetup next week. I suggest sending it the day after, on Thursday (January 19).

**Comment by colin-kiegel** [comment]
Ok, I have started an invitation text (first post).

Shall we provide any introductory material or prepare a little demo respository? Tips and Tricks (like commonly used libraries in procedural macros)?

I found this introduction, though slightly outdated (e.g. no feature gate anymore): https://users.rust-lang.org/t/macros-and-syntax-extensions-and-compiler-plugins-where-are-we-at/7600

**Comment by Florob** [comment]
I haven't looked at Macros 1.1 myself yet. Seems like a great topic though.
I think it would be good if someone could prepare a short introductory talk covering the what, why, and how. Having reference material available is good too, but I think it would be unfortunate if everyone spend the first minutes buried in paper or a laptop to read up on the general concepts.

**Comment by killercup** [comment]
Good point. Steve recently added this chapter to the docs (note the "beta"): https://doc.rust-lang.org/beta/book/procedural-macros.html

Maybe we talk about about the what and why, and then one of us can go through the book's example on the beamer?

**Comment by dtolnay** [comment]
I gave a 24-minute talk at the most recent San Francisco meetup: [Macros 1.1 + Syn + Quote](https://air.mozilla.org/rust-meetup-december-2016-12-15/). Slides are [here](https://github.com/dtolnay/talks#macros-11--syn--quote) but are almost entirely code so they don't stand alone as a resource. Feel free to adapt the slides and run through them (in German?) if you think it would be helpful.

**Comment by badboy** [comment]
@dtolnay Thanks! Having examples at hand is always useful.

@others: Macros it is!

**Comment by colin-kiegel** [comment]
:tada:

@badboy: `others` is actually a github user. Seems to live in portland, so I'd be surprised if he joins us. But I guess he gets quite a lot of mentions. ^^

**Comment by dtolnay** [comment]
I live in the same time zone as Portland and this meetup will be 10:15 in the morning here, so **@&#8203;others** and I will both be available to merge syn/quote PRs, fix bugs, answer questions etc.

**Comment by badboy** [comment]
Well, that mention to @others was not intended. Sorry!

@Rustaceans/organizers-cologne: Macros it is!

**Comment by killercup** [comment]
I updated the title and parts of the description. Will submit a PR to add it to the website as well, which we can merge at the end of the meetup next week so the site gets updated.

**Comment by killercup** [comment]
Merged the PR to update the website with this event and I [may](https://twitter.com/RustCologne/status/822052310616522752) have also mentioned it on twitter.

**Comment by colin-kiegel** [comment]
only reddit and rustplatz missing now. I can do rustplatz this weekend.

**Comment by killercup** [comment]
Thanks, @colin-kiegel. I posted it to rustplatz and reddit.

**Comment by mre** [comment]
Just stumbled upon the following article by @steveklabnik: http://words.steveklabnik.com/an-overview-of-macros-in-rust
Might be a good resource for our next meetup. (Thanks Steve!)

**Comment by colin-kiegel** [comment]
# Picks

## Meetups
- Rust Cologne Meetup
- [hackover.de](https://hackover.de/) (next meetup in Hannover)

## Tools
- spacemacs
- racer + vim
- curve25519-dalek in Rust

## Books / Blogs
- thursday next (book)
- learn you a haskell for great good! (book)
- niko matsakis blog (http://smallcultfollowing.com/babysteps/)
- rust internals list

## Crates
- [derive builder](https://github.com/colin-kiegel/rust-derive-builder)
- [validator](https://github.com/Keats/validator)
- [faker](https://github.com/tikotzky/faker-rs)
- [tera](https://github.com/Keats/tera) (templating library)

## Others
- image library from piston project (migrated to Rust)
- get children
- avoid winAPI
- curry sausages around the corner
- Gstreamer
- vulkan API (complicated, fantastically well designed)

**Comment by badboy** [comment]
Thanks for noting those down!

**Comment by colin-kiegel** [comment]
[here is my talk .. ](https://gist.githubusercontent.com/colin-kiegel/36379706f54a03c9339e38c5e231c457/raw/ea4abd36b1d05b65dd479cd87c482e45a300a9a1/rust_macros_1.1.html)

**Comment by chridou** [comment]
Currywurst, not Hot Dogs ;-)

**Comment by mre** [comment]
Oh yeah and the templating engine is called [tera](https://github.com/Keats/tera), not terra. ;-)

**Comment by colin-kiegel** [comment]
thx - fixed those two things. :-)
