### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by brakmic** [Rustaceans/rust-cologne#27]
Hello everyone,

Our current subtitle is: *The recurring Rust **enthusiast's assembly** in the fair city of Cologne, Germany*

If I'm not completely mistaken this should rather be:

*The recurring assembly **of Rust enthusiasts** in the fair city of Cologne, Germany*

I think the contraction **enthusiast's** is superfluous.

So, if we'd keep the original subtitle I'd write:

*The recurring Rust **enthusiasts assembly** in the fair city of Cologne, Germany*

However, I think that native speakers would rather prefer to use the preposition **of**. 

But, there are no native speakers among us, AFAIK. 🙄

**Comment by colin-kiegel** [comment]
Thx. We should ask a native speaker if we have the opportunity e.g. during one of our next meetups. ;-)

**Comment by badboy** [comment]
I brought this up in `#rust-community` yesterday, as we have native english speakers there.
They all said that the second one sounds best and most natural.

> The recurring assembly of Rust enthusiasts in the fair city of Cologne, Germany

**Comment by killercup** [comment]
> "recurring assembly of Rust enthusiasts in the fair city of"

> sounds best and […] natural

🤣

Also, I just messed up the apostrophe position and wanted to use genitive plural (i.e., "Rust enthusiasts' assembly") which sounds fancier than the version using "of". To be honest, if we want to use a simpler form (with "of"), we should also consider not using unusual words like "recurring", "assembly", and maybe even "enthusiasts" 😉

…but I'm totally fine with changing it to "of Rust enthusiasts" and to change it you probably only need to edit the `config.yml`.

**Comment by colin-kiegel** [comment]
What I like about the original order is that `Rust enthusiasts` is more center stage at the beginning of the sentence.

I would be good if we just fix the apostrophe.

In the end our audience is mostly German speaking. So while we should correct mistakes we don't need to stick with the native speakers recommendation as long as it sounds good to us and is allowed. That would be my pragmatic reasoning. :-)
