### ISSUE TITLE
Google API Key für Maps

### ISSUE THREAD

**Issue by brakmic** [Rustaceans/rust-cologne#3]
Google scheint den jetzigen API-Key nicht zu mögen.

Zumindest sehe ich das, wenn ich darauf zugreife.

``` shell
The Google Maps API server rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxx.xxx.xxx.xxx, with referer: https://www.google.com
```

**Comment by killercup** [comment]
Interessant. Bei mir funktioniert's.

> This IP, site or mobile application is not authorized

Kannst du das mit dem selben Gerät in einem anderen Netzwerk testen? Vielleicht liegt es tatsächlich an deiner IP? (Ich weiß nicht, wie Google das bemisst und wieviel Google Maps du heute schon benutzt hast. 😄)

**Comment by brakmic** [comment]
Ich habe es mal mit einem Proxy versucht und es geht. Keine Ahnung, warum Google meine IP blockiert. Na ja, dann schließen wir diesen Fall :smile:
