### ISSUE TITLE
Crate Polishing Workshop

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#30]
We might want to tackle a Crate Polishing Workshop.
See http://llogiq.github.io/2017/02/27/cpw.html

>  fmt, clippy, fuzz, test, bench

**Comment by killercup** [comment]
Seems legit, has a three letter abbreviation 👍

Any crates in particular that you guys want to tackle? Something one of us is the owner of? I have a bunch of semi-loved repos lying around, but [I'm](https://github.com/killercup?utf8=✓&tab=repositories&q=&type=source&language=rust) [not](https://github.com/badboy?utf8=✓&tab=repositories&q=&type=source&language=rust) [the only](https://github.com/colin-kiegel?utf8=✓&tab=repositories&q=&type=source&language=rust) [one](https://github.com/florob?utf8=✓&tab=repositories&q=&type=source&language=rust) 😄

Also, let's make some relevant cross-link magic happen: <https://github.com/Rustaceans/rust-cologne/issues/29#issuecomment-284165276>

**Comment by killercup** [comment]
Just came across [this evaluation of the tempdir crate](https://public.etherpad-mozilla.org/p/rust-crate-eval-tempdir) by the libs team, and [this list of guidelines](https://github.com/brson/rust-api-guidelines) it uses.

**Comment by mre** [comment]
The list of guidelines has enough topics for a full book on idiomatic Rust libraries. 😳  Pure craziness.

**Comment by colin-kiegel** [comment]
crate candidates
- https://github.com/dborzov/rusticsearch
- lopdf (?)
- rpck (compressor)
- byteorder
- [errorchain](https://github.com/brson/error-chain) ✓
- [toml](https://github.com/alexcrichton/toml-rs) ✓

**Comment by colin-kiegel** [comment]
@Rustaceans/organizers-cologne shall we close this or leave it open for next time?

**Comment by badboy** [comment]
Close this for now.
