### ISSUE TITLE
2nd Anniversary T-Shirt

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#32]
We discussed this a bit in #26, I'll quote it here for convenience:

@mre in <https://github.com/Rustaceans/rust-cologne/issues/26#issuecomment-292903904>:

> Would also be interested in a T-Shirt!
> We could either go with the Rust Cologne logo, or print something more generic.
> I really liked the [steampunk design](https://devswag.com/products/rust-t-shirt) from Rust 1.0.
> 
> I could create a simple artwork based on these free vector graphics:
> * [octopus](http://www.freepik.com/free-vector/background-of-hand-drawn-octopus-with-gears_958929.htm#term=steampunk&page=1&position=3)
> * [gears](http://www.freepik.com/free-vector/background-of-machine-gear_956706.htm#term=steampunk&page=1&position=42)
> 
> In any case, it's a lot of work, so I would like to know upfront if you are interested in that. If so, which design do you prefer?

@killercup in <https://github.com/Rustaceans/rust-cologne/issues/26#issuecomment-292934489>:

> Nice! I like the steampunk style and think the octopus looks quite cool;
> might be hard to add a rust flavor, though (aside from the cogs).
> 
> That reminds me, did you all see the cyberpunk style of the reddit on April
> 1st? Might also be cool to do something like that. (Which is also
> historically accurate, as cyberpunk came after steampunk after all!)
>
> [[see here for archived version](http://archive.is/A0stm)]

@mre in <https://github.com/Rustaceans/rust-cologne/issues/26#issuecomment-293380049>:

> Sooo, you like the 80's style logo?
> 
> Like [this](https://de.pinterest.com/pin/294774738084037269/), [this](https://www.google.de/imgres?imgurl=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2F736x%2F0a%2F08%2F2a%2F0a082ad60878b2d7a24c35d3fda0ce80.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fadoraattack%2F80sretroelectro%2F&docid=8yBGIjekIySggM&tbnid=JtQEEVYiGQts7M%3A&vet=10ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhJKBgwGA..i&w=500&h=400&client=firefox-b-ab&bih=787&biw=1203&q=miami%20vice%20logo%20style&ved=0ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhJKBgwGA&iact=mrc&uact=8) and [that](https://www.google.de/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fy8brTm5aslo%2Fmaxresdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dy8brTm5aslo&docid=QPBZ0Cx0w0D3FM&tbnid=jnTfvHdqQmplyM%3A&vet=10ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhtKDwwPA..i&w=1920&h=1080&client=firefox-b-ab&bih=787&biw=1203&q=miami%20vice%20logo%20style&ved=0ahUKEwiey7Ppk53TAhUD6xQKHbX8A1kQMwhtKDwwPA&iact=mrc&uact=8)?
> There's a [video tutorial](https://www.youtube.com/watch?v=y8brTm5aslo) for that.
> 
> That said, not a big fan to be honest. People might confuse it with GTA Vice City fan shirts. On the other side... maybe that's exactly your point?
> In case you mean the "Matrix" and "Hackers" photos as well, that's gonna be a bit tricky on colored shirts, I guess.

**Comment by killercup** [comment]
(Brain dump ahead. @mre, it's okay to just reply to this with "Pascal, stop drinking before lunch" 😆)

I just saw [the cover](https://f4.bcbits.com/img/a0311173342_10.jpg) of [this album](https://maxthor.bandcamp.com/album/another-world), showing a futuristic landscape at the end of a tunnel with a sun right in the middle with a person floating in front of it.

I know it's a tall order, but maybe we can do something visually similar to this? I can think of a whole bunch of things we could do, and how to interpret it. E.g., one prominent building could look like the Cologne cathedral, and the tunnel could be seen as the end of an ethernet cable (cyberpunk style connecting reality with a virtual world). And Rust is sometimes described as "saving the future with forgotten [computer science] knowledge from the past", so we could play with a mixing of styles (add a steampunk zeppelin for good measure).

**Comment by mre** [comment]
This is... I don't even... you should definitely consider medical examination.
We should definitely watch the new Blade Runner movie together.
Also, you're overestimating my Photoshop skills. 😆 But hey! I'm all in favor trying some wild idea.
Just a bit skeptical about the print. Usually vector graphics would be easier to handle.

**Comment by Florob** [comment]
So, for my crazy idea: How about something circuit board-y?
[Sketch](http://babelmonkeys.de/~florob/rust-circuit.svg)

**Comment by killercup** [comment]
Eh, so, the 2nd anniversary is over. Do you want to keep this issue open to collect more ideas and maybe do a t shirt for another occasion? (E.g. (but probably already to late), [Rust 1.18](https://blog.rust-lang.org/2017/06/08/Rust-1.18.html)… 18… Wait a second! Rust is old enough to drink liquor!)

**Comment by mre** [comment]
Have to say I feel very bad for the missed opportunity. On the other side, it's never too late for a cool Rust T-Shirt. Two reasons this project was failing: First we could not agree on a design, second it was lots of work and we're all busy people.

So here's my idea to resolve both issues at once: let's keep it simple.
We'll take orders until the next meetup and then we print a shirt like this, but using the Rustlang logo. Deal?

![grafik](https://user-images.githubusercontent.com/175809/26952941-efe40fda-4ca7-11e7-952a-0ae4720eef75.png)

**Comment by colin-kiegel** [comment]
I like the idea to keep it simple and just use a logo.

What about the Rust Cologne logo? The colors could be inverted, since dark shirts might be more popular, I guess. I also like the light grey on dark grey in the previous github example. :-)

![](https://secure.meetupstatic.com/photos/event/2/1/8/2/global_458468578.jpeg)

**Comment by killercup** [comment]
Let's try this again next year :)
