### ISSUE TITLE
Be part of the Worldwide Meetup

### ISSUE THREAD

**Issue by killercup** [Rustaceans/rust-cologne#33]
The Rust Community team is planning a worldwide meetup using several locations, video streaming, and a bunch of speakers. (Thanks @colin-kiegel for forwarding @erickt's mail!)

Do we want to be part of that?

They haven't settled on a date yet, but it sounds like it's about to be in September. I assume the C4 would be a good location, with fast Internet and even professional camera setup (cc @Florob).

Here is the roadmap: https://github.com/rust-community/team/milestone/4

**Comment by Florob** [comment]
I'm all for it. I'll ask if the C4 would be willing to host this. There should certainly be enough room, and the possibility to host a local speaker.

**Comment by badboy** [comment]
I'd be happy if Rust Cologne takes part as well. I will not be on-site personally in the fall, but of course I would be happy to take care of communication and sponsorship things.

**Comment by mre** [comment]
@colin-kiegel closed by accident?

**Comment by colin-kiegel** [comment]
Oh, right - I thought this was about the 2nd anniversary. But this seems to be still ahead [around end of September](https://github.com/rust-community/team/issues/135)! :-)

**Comment by killercup** [comment]
Let's close this issue until we have worldwide meetup in 2018 :)
