### ISSUE TITLE
custom meetup nametags

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#38]
@Rustaceans/organizers-cologne, cc @mre

Hi everyone,

I just sat down and experimented with a custom design for our **meetup nametags**. I had this idea for a while now.

![meetup-tag_v3](https://user-images.githubusercontent.com/7691186/29275217-ad9ea24c-810a-11e7-98df-3c8ca7e396ab.png)

And we could even have some geeky Rust code on the nametags, [like this ^^](https://play.rust-lang.org/?gist=3b0f5df5f5f297c33970f241b6cb2497&version=stable).

The idea would be to print blank nametags and let our participants fill out their names, because the pre-filled nametags from meetup only support a fixed design (red+white, no logo).

If you like the idea, I could iterate a little more on the design. What do you think about it?

Btw., here are some earlier drafts:
<details>
<summary>Draft 1</summary>
<img src="https://user-images.githubusercontent.com/7691186/29274794-4ccf467a-8109-11e7-94d7-ded3e53b232e.png">
</details>

<details>
<summary>Draft 2</summary>
<img src="https://user-images.githubusercontent.com/7691186/29274795-4cd2d9b6-8109-11e7-9e10-07bfaa1a6908.png">
</details>

**Comment by colin-kiegel** [comment]
PS: The format of the nametags is roughly **10.5 cm** x **7.4 cm**

**Comment by badboy** [comment]
Hey, cool idea! I already like the current design. Maybe the stroke can be a bit more evenly.

**Comment by killercup** [comment]
Nice! I like the first version best :) (It's also always good to leave lots of white space for people to get creative!)

**Comment by colin-kiegel** [comment]
ok, **less curvature** and **more whitespace** is noted. :-)

Also **repetitions should look smoother** (as in a wallpaper), because the cutting line of the nametags may be misaligned by 1-3 mm from the ideal line. So something like a sine-curve might work better than an ellipsis etc. Its also the reason, why I already put orange bars both on the top and the bottom.

@killercup hm, _first version_ is a bit ambiguous. ^^ Just to make sure, you mean what I Iabeled as "earlier draft 1", right?

**Comment by killercup** [comment]
Ah sorry, @colin-kiegel, I meant first in the sequence of shown images, not chronologically :) I.e., [this one](https://user-images.githubusercontent.com/7691186/29275217-ad9ea24c-810a-11e7-98df-3c8ca7e396ab.png).

**Comment by colin-kiegel** [comment]
PS: What do you think about this as a background code-snippet?

```rust
// please let us know your name ;-)
const MY_NAME: &str = stringify!(


                Dummy User


);

fn main() {
    println!("Hello everyone, my name is {}!", MY_NAME);
}
```

The `stringify!` is so that whitespaces don't matter. ^^

**Comment by colin-kiegel** [comment]
Ok, the new version looks like this - what do you think?

## A1: with code-snippet
![meetup-tag_v4a](https://user-images.githubusercontent.com/7691186/29719151-588e0eec-89b5-11e7-96d4-928e3e8c32cc.png)

## A2: with code-snippet + subtle syntax highlighting :-)
![meetup-tag_v4a2](https://user-images.githubusercontent.com/7691186/29719623-2cf25e8a-89b7-11e7-81ab-54caf8282c83.png)

## B: simple
![meetup-tag_v4b](https://user-images.githubusercontent.com/7691186/29719155-5c857cec-89b5-11e7-9163-7f810e085f09.png)

**Comment by Florob** [comment]
I quite like version A2. I think the code needs some more contrast, but that might just be my perception because the PNGs have a transparent background.

**Comment by killercup** [comment]
A2 is my fav, but with a darker color for the string literal. Also: test how this looks when printed in the correct size. I wouldn't be surprised if it became really hard to read.

**Comment by colin-kiegel** [comment]
Alright. :-)

I will make some test prints and if it looks good, I will bring different sheets with different contrast to the next meetup.

@killercup shall I check-in the final SVG / pdf into this git repo? If yes, would some sub-folder be ok, or do you prefer a standalone branch?

**Comment by killercup** [comment]
@colin-kiegel cool! A subdirectory sounds good. We already have `assets/` for website downloads (slides and cake pictures), so maybe `organization/`?

I've recently see that the web engineering Düsseldorf meetup made [a repo](https://github.com/WebEngDUS/WebEngDUS) for all their assets, checklists, speaker info etc. and I think we too could add more of that to our repo. This would also give us the opportunity to discuss concrete changes to these files as pull requests.

For example:

- Add Github Issue template with the check list for events
  - just drop this in as `issue_template.md` (or `.github/issue_template.md`), see <https://help.github.com/articles/creating-an-issue-template-for-your-repository/>
  - this could also be our canonical "organization workflow" document
  - feel free to symlink this to/from `organization/`
- your amazing name tag assets
- @Florob's great recording assets (#28)

**Comment by colin-kiegel** [comment]
Seems like everyone liked the new nametags. I've uploaded them unchanged and I will print some more next time. Maybe we can store some sheets at the c4, to make them available when I'm not there. :-)

It's all in a folder [`meetup-orga`](https://github.com/Rustaceans/rust-cologne/tree/gh-pages/meetup-orga), which also links to a new [`.github/issue_template.md`](https://github.com/Rustaceans/rust-cologne/blob/gh-pages/.github/issue_template.md).

---

I'll leave it to @Florob to add the recording assets, if he wants to. :-)
