### ISSUE TITLE
Domain removal

### ISSUE THREAD

**Issue by brakmic** [Rustaceans/rust-cologne#43]
# Important

It seems that some people from my web provider have decided to delete **rust.cologne**. However, this makes no sense as I have expected them to renew the contract automatically. So, in the mean time, until they have finally realized that I didn't want **rust.cologne** to be deleted, the stuff from GitHub won't be accessible.

Although I'm not very active in the Rust space (*too old for good stuff*) I'll take care of this domain for another year. After that we can talk about what should happen with it.

Best,
Harris

**Comment by colin-kiegel** [comment]
@brakmic thanks for the update and for dealing with this.

As a side note: Mozilla offered us some financial support, should we need it. We could ask for a refund of the hosting costs. Just contact @badboy how to do this.

**Comment by brakmic** [comment]
Hi @colin-kiegel,

Many thanks ❤️ 

Ah, complex stuff, Mozilla & finances. 😅 

Maybe I should ask them to send me some fluffy toy like this one:

![fox](http://www.happyworker.com/sites/default/files/styles/940x450/public/slideshow/mozilla-firefox-plush-front.jpg?itok=SD2R1DkW)

**Comment by badboy** [comment]
Well, I can take care of Mozilla if you want.
If you drop me an address I'll get you [a Firefox plushie](https://pbs.twimg.com/media/DNIT_FOWsAAv5OG.jpg:large) and (once they arrive) [a Ferris](https://ksr-ugc.imgix.net/assets/016/418/023/28c41642a3c8d4407ae379e053108eec_original.jpg?crop=faces&w=1552&h=873&fit=crop&v=1493252740&auto=format&q=92&s=26236ee1b5cfaa253829663afb8a6d7a) anyway.

**Comment by brakmic** [comment]
@badboy,

Great! Many thanks ❤️ 

My daughter will love it. 😃 

Here's the address: 
*removed*

**Comment by badboy** [comment]
Perfect. (I went ahead and removed your address from public record, no need for it to be seen here ;))

**Comment by killercup** [comment]
Thank you, Harris! I can only offer stickers and a warm invitation to our
December meetup. If you want to transfer the domain in the future (no idea
if .cologne domains do something special here), let me know.

Jan-Erik Rediger <notifications@github.com> schrieb am Sa. 4. Nov. 2017 um
11:21:

**Comment by brakmic** [comment]
Many thanks, Pascal!

I'll try to attend the meeting. 🍺 🐟 🍖 

The domain was reactivated, but it'll take some time until DNS servers get their updates done.
In Nov. 2018 we'll see what should happen with the domain. 😅

**Comment by brakmic** [comment]
So, the website is available again. 😄 

Cheers,
