### ISSUE TITLE
We need our Logo as Stickers!

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#45]
We need our logo as small and big stickers. Gonna take care of that.

**Comment by killercup** [comment]
Awesome! Please make sure to send a batch of (at least) 50 stickers to every organizer for inspection before printing any larger amounts (>10.000).
  
FYI, added black logo as svg/pdf and signs and other stuff [here](https://github.com/Rustaceans/rust-cologne/tree/16ad55bfe36a8599623892c63982bfd65844dadb/meetup-orga).

**Comment by badboy** [comment]
Absolutely! 💵 💰 💸

**Comment by killercup** [comment]
Have received stickers at RustFest and have been dispensing them at meetups, so this can be closed :)
