### ISSUE TITLE
Call for Contact Info

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#47]
The community team is trying to improve outreach to meetup organisers. Please fill out their [call for contact info](https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform).

**Comment by killercup** [comment]
I assume this happend and the right people have replied and everything is right in the world
