### ISSUE TITLE
Twitter security 

### ISSUE THREAD

**Issue by liamsi** [Rustaceans/rust-cologne#55]
Heyhey 👋

As most of you might have heard there were some security problems on twitter's side. We also got notified (I received this notification as I still own the twitter account):
![image](https://user-images.githubusercontent.com/7441766/39716394-27c1adbe-5228-11e8-8e85-ee66d6c439d4.png)

I propose to change the password & turn on 2fA. Also, instead of sharing the PW with everyone that posts from this account we could switch to using tweetdeck. It might make sense to add another recovery email address to this twitter account (@killercup ?). Let me know what you think. We can also move this discussion offline (some of you might still have my phone number).

Keep up the good work 💪

**Comment by killercup** [comment]
Hi! Thanks for the notice -- feel free to set my email as a recovery address. I've also been had this account in my tweetdeck for a while now :)

**Comment by Florob** [comment]
I've also been using the Twitter account exclusively via Tweetdeck. I'm not even sure I ever had the password. so feel free to change it.
Thanks for the heads up.
