### ISSUE TITLE
Get a TLS cert from Github for the custom domain

### ISSUE THREAD

**Issue by FichteFoll** [Rustaceans/rust-cologne#66]
Via https://github.com/isaacs/github/issues/156, it has been possible to get issued a certificate for a custom domain for a few months now. I'm not entirely sure about the process, but maybe it's enough to just disable and re-enable the custom domain in the repository's preferences?

https://help.github.com/articles/troubleshooting-custom-domains/#https-errors might also have something about this.

**Comment by killercup** [comment]
Ah, thanks for the reminder!

@brakmic, you currently manage the rust.cologne domain and said in #43 that you wanted to do so for another year (November 2018). Do you want to transfer it to one of us? Also, can you change the A records of the domain to (one of the) IP addresses listed [here](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) to enable Github's HTTPS support?

**Comment by brakmic** [comment]
Hi,

The domain is registered until 04. of Nov. 2018. But I can give you the Auth-Code so you can take over.

**Comment by brakmic** [comment]
I have also changed the IPs.

**Comment by killercup** [comment]
Awesome, thanks, @brakmic! I'll send you an email.

Meanwhile, Github says

> [HTTPS:] Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete.

**Comment by killercup** [comment]
Sweet, https://rust.cologne now works for me!

Thanks for the quick response, @brakmic!
