### ISSUE TITLE
Meetup October

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#7]
Invitation (draft)

> Join our **open space** style meetup on the first Wednesday of October, 2016-10-05.
> 
> Imagine a bazaar, where you can suggest topics and spontaneously join any discussion you find interesting. It all depends on your interests.
> 
> Some possible activities and topics have already been suggested in advance:
> - IDE support and best practice configurations
> - group code review of a WIP project
> - ... your suggestion?
> 
> We will have timeslots of 30 minutes to allow you to engage in different discussions. :-)
> 
> We are looking forward to seeing you. As always you can enjoy some drinks and get to know other nice people interested in Rust.
> ---
> 
> The meetup will likely be held in German, we will however reevaluate this at the beginning of the evening and may switch to English if needed.

Orga
- [x] Send "Save the Date" info (with link to this ticket)
- [x] Basic Agenda
- [x] Decide who does the "moderation" of open space
- [x] Approve invitation text
  - [x] badboy
  - [x] colin-kiegel
  - [ ] florob
  - [x] killercup
- [x] Final invitation (deadline Sept 28)
  - [x] [meetup](http://www.meetup.com/de-DE/Rust-Cologne-Bonn/events/233897575/)
  - [x] [website](http://rustaceans.cologne/2016/10/05/open-space.html)
  - [x] [twitter](https://twitter.com/RustCologne/status/779719453277818880)
  - [x] [community calendar](https://calendar.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc@group.calendar.google.com&ctz=Europe/Berlin)
  - [x] [reddit](https://www.reddit.com/r/rust/comments/54aseo/meetup_in_cologne_wednesday_oct_5th_2016_at_715pm/d8096dl)
  - [x] [rust-lang forum](https://users.rust-lang.org/t/cgn-11-open-space-rust-meetup-wednesday-2016-10-05/7394)
  - [x] [rustplatz](https://forum.rustplatz.de/t/koeln-11-open-space-rust-treffen-wednesday-2016-10-05/173)

**Comment by colin-kiegel** [comment]
just send the save-the-date info ... hope everyone is fine with the text ;-)

**Comment by killercup** [comment]
Added the event (with @colin-kiegel's description and a link to this issue) to the website.

**Comment by carlberger** [comment]
Hey, 
I offered to "organize" the meeting as an open space, if you guys agree. I would try to make the "organize" part very short (5-10 minutes) in order to have everybody understand the way such a thing works. In short: the things we are gonna talk about will be decided up front on the spot, and the themes will be discussed in groups, and everybody can join the discussion they are interested in. These discussion happen in parallel, in 30 minutes slots. If a group decides to talk any further they are free to do so, and anybody can leave and join any discussion at any time. I attended some open spaces, and this pratice has been served very well, but we are open to change the rules on the spot if we want to. 
Mandatory wikipedia link: https://de.wikipedia.org/wiki/Open_Space  
Are you okay with this ? 
cheers,
carl

**Comment by colin-kiegel** [comment]
@carlberger I'm definitely ok with you doing the open space moderation. And you are also the first who volunteered.

@Rustaceans/organizers-cologne 
- other opinions on this part?
- I updated the invitation text in the first comment - it is now a draft for the final invitation and ready for your review and/or approval. :-)

**Comment by killercup** [comment]
Invite and plan look good to me (I fixed typos along the way).

**Comment by colin-kiegel** [comment]
I send the final invitation via 4 of 7 channels, @killercup do you want to do the remaining 3 as usual? :-)

**Comment by colin-kiegel** [comment]
@carlberger it seems like everyone is ok with you doing the moderation. Thank you very much for your suggestion and commitment. :tada:

**Comment by badboy** [comment]
Sorry for being so silent. Thanks for getting this out. :tada:

**Comment by killercup** [comment]
Blasted out a bunch of announcements all over the other channels :)

@Rustaceans/organizers-cologne, I think by now all of you have access to the twitter account. Feel free to tweet out reminders of the event at convenient times (when you think most people will see them) or retweet other related stuff (like cool things our community members do).

I think it'd also make sense to try to gather some suggestions for topics up front (and collect them here).

**Comment by carlberger** [comment]
Thank you for organizing this event and for trusting me in this open space thing, I hope It'll work out as I promised :)

**Comment by killercup** [comment]
@Rustaceans/organizers-cologne, I've collected a few notes on possible topics for the meetup (and what to say at the "This month in Rust" section): http://pad.fnordig.de/p/rust-cologne-2016-10-topics

This is not meant to require people to write down their topics beforehand, just to help people like me who are bad at coming up with stuff on the spot :) Feel free to share the link (maybe also on meetup.com?) and add to the pad.

**Comment by colin-kiegel** [comment]
@carlberger Hi Carl, thanks for moderating the open space part. I enjoyed it very much and I think it worked quite good even in our small group. We didn't stick very much to the timetable, but it was good to know what everyone wanted to talk about in advance. So, thank you again. I think we can repeat that in the future! :-)

PS: I hope you enjoyed the evening as well.

**Comment by carlberger** [comment]
@colin-kiegel thanks! I thought it went quite well, too! According to the rules, anything what happens when the OS has started is right. The marketplace with its timetable is some kind of guide to be sure that all the topics on the board have a chance to get discussed, which we managed succesfully, I think. Gerne wieder :)
