### ISSUE TITLE
Question: Can I reuse this website code

### ISSUE THREAD

**Issue by mattgathu** [Rustaceans/rust-cologne#73]
Hello, I'm creating the Rust Nairobi user group website and wanted to know if it's okay to 
reuse the code for Rust Cologne website.

There is no License file so I thought wise to ask.

Thanks

**Comment by killercup** [comment]
Hey Matt, sure!

Some time ago we even extracted the Jekyll template: https://github.com/rust-community/rust-meetup-template

berlin.rs uses our template, too :)

PS: You can easily change the colors by overwriting this variable: https://github.com/rust-community/rust-meetup-template/blob/8399ad00b80b11c370beff982380f192c91f739f/_includes/styles.scss#L10

**Comment by mattgathu** [comment]
cool! Thanks 🦀
