### ISSUE TITLE
Release September Recordings

### ISSUE THREAD

**Issue by Florob** [Rustaceans/rust-cologne#8]
Recordings should be released on https://media.ccc.de/c/rustmcb. This issue is mostly for visibility/my own benefit.
- [x] Create prerolls/postrolls
- [x] Cut Videos
  - [x] "Why I hate GCs"
  - [x] "Compiling Rust to asm.js"
- [x] Render master encodings (mp4)
  - [x] "Why I hate GCs"
  - [x] "Compiling Rust to asm.js"
- [x] Render subformats (webm)
  - [x] "Why I hate GCs"
  - [x] "Compiling Rust to asm.js"
- [x] Release on media.ccc.de
  - [x] Create thumbnail and poster images
  - [x] Upload
  - [x] Create backend entries

**Comment by Florob** [comment]
And we have liftoff.

**Comment by colin-kiegel** [comment]
wow, this is awesome - even with picture in picture. good job. :-)

**Comment by badboy** [comment]
Thanks, Florob! Great work once again.
