### ISSUE TITLE
March 2020

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#87]
https://twitter.com/timClicks/status/1196915457401344000

> hallo! ich werde in Deutschland im März nächstes Jahr sein. gibt's einen freien Talkslot?

/cc @timClicks

**Comment by mre** [comment]
That would be great!

**Comment by timClicks** [comment]
Awesome! I have a work event 2-6 March in Frankfurt. Would it be possible to schedule something between 7-9 March? I'll take the train north and spend a few days in DE before heading home to NZ.

**Comment by Florob** [comment]
@timClicks
Indeed we'd be happy to have you.
I'll have to check with the venue, but 7-9th March sounds plausible. Any preference? Otherwise I'd ask around at the next meetup whether people would prefer a Monday evening, or the weekend (potentially earlier in the day).

**Comment by timClicks** [comment]
The weekend would work well for me too. I am preparing a [90 minute tutorial for Linux.conf.au](https://linux.conf.au/schedule/presentation/89/) that I could present in Germany.

**Comment by Florob** [comment]
Repurposing this as the general March planning ticket

@timClicks First of all sorry for being so late with this. I'm way worse at time management then I'd like to be.
The tutorial sounds like a nice fit for us. I've also heard from some people that are not regulars at the meetup that they would be interested in something like this.
I'd propose starting March 8th at 16:00 if that works for you. Leaving some time for people to learn/play around with guidance available after the tutorial.
We have the possibility to do decent recordings if that is something you are interested in. Personally I feel like its often detrimental to a tutorial format though.
If you have time a short abstract for the announcement would be nice, or just tell me to use (something like) the linux.conf.au one.

**Comment by kawogi** [comment]
Next Meetup will be held on March 8th?
https://rust.cologne/ still points to Feb 5th. Maybe someone™ finds the time to update the date :)

**Comment by Florob** [comment]
@fyl2xp1 Pushed a commit to trigger the "currently planning" rebuild. Other than that I know nothing that isn't tracked in this ticket. So I can't really update the date to something that wouldn't be a guess.

**Comment by YtvwlD** [comment]
You are aware that Meetup is sending out notifications for tomorrow?
![grafik](https://user-images.githubusercontent.com/5578100/75777228-e2fc2480-5d55-11ea-93b6-9e83db2dbccf.png)

**Comment by Florob** [comment]
@YtvwlD I'm generally aware of it sending out notifications, sometimes a few days ahead of time, sometimes the day before. I am also aware the date is still wrong. Thing is changing the date of the event also generates a notification, so I'd rather only do that once.
At any rate I'll announce something this evening including a date change. If I don't hear anything 'til then it will just be "Hack and Learn" on Sunday.

**Comment by timClicks** [comment]
I'm really sorry all, I won't be able to get to Cologne this weekend. I will be stuck in Frankfurt :(

**Comment by Florob** [comment]
@timClicks Sorry to hear that. Would've liked to know that earlier, but that's on me for confirming this late. Have a good time in Frankfurt.
