### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by colin-kiegel** [Rustaceans/rust-cologne#9]
I just saw the rainbow rust wheel in the videos. Is this our logo? Should it be?
We could put it on our website + meetup if everyone from the orga team is ok with rainbow colors? 

It would be ok for me.

cc @Rustaceans/organizers-cologne

**Comment by xetra11** [comment]
What about this mystical one: https://github.com/brson/temple-of-rust

or the crab!

**Comment by killercup** [comment]
As with most symbolic images we should be very careful what we choose to use: There are licensing/trademark, implied meanings, similarity to other symbols, and many other aspects to consider—as well as some things specific to a logo (e.g. discernibility at different sizes).

**Comment by colin-kiegel** [comment]
@killercup right, we have to be careful. We could double check with the rust community team if there are any guidelines what modifications and use of the official rust logo are permitted.

I think the logo should give a hint on "rust" and on "cologne". The temple of rust or the crab don't have any reference to cologne. A rainbow colored rust cogwheel has - at least to _some_ aspect of cologne. ^^

Maybe we can combine the rust cogwheel with some simplified [cologne skyline (CC0)](https://pixabay.com/p-524243/?no_redirect) inside? Something in the spirit of the [travis rust mascot](https://blog.travis-ci.com/2014-09-3-travis-ci-gets-a-little-rusty/)?

And we could ask our members to hand in suggestions. Maybe with some basic criteria (like the @killercup listed)?

**Comment by badboy** [comment]
_community team hat on_ the community team can't give permission, but we certainly know the right folks to ask. I will take care of that. _community hat off_

I'm against the temple of rust. People already know that unrelated to our user group.
I like Colin's ideas of combining the colored version with some cologne branding.

**Comment by badboy** [comment]
@Florob can you give me a version of the colored version for use in the youtube playlist?

**Comment by badboy** [comment]
Oh and regarding the logo modifications: It is CC-BY and trademarked. We need to “give appropriate credit, provide a link to the license, and indicate if changes were made”, which, if we take it as our official logo, can be done on the website.

See https://www.rust-lang.org/en-US/legal.html

**Comment by badboy** [comment]
@Florob nevermind about the logo, it is not necessary.

**Comment by mre** [comment]
Just stumbled across this issue and thought I'd give it a shot.
Find the result attached.

<img width="687" alt="rendered" src="https://cloud.githubusercontent.com/assets/175809/23102893/dce8ecee-f6b1-11e6-9c5f-2e9d18457eca.png">

As @colin-kiegel  suggested, I took the official Rust cogwheel as a template. I've added the dome from here: https://thenounproject.com/search/?q=cologne&i=11885
The license of the dome is Public Domain. You can also use my logo under Public Domain. No reference required.

Personally I like the simple black style. The rainbow logo looks a bit "trippy" and it's hard to decipher at smaller sizes. But feel free to disagree.
If you're interested in using the logo, I can push the vector graphic somewhere. If not then at least I brushed up my rusty Inkscape skills a bit (this joke is getting old).

**Comment by colin-kiegel** [comment]
@mre I'm impressed. I like it very much to say the least. :-)

PS: The intention of this issue was to wait for someone talented and interested to stumble upon it. Hooray it worked.  :-)

**Comment by killercup** [comment]
Woah, awesome, @mre! I really like the b/w version. Can you do a version with the lower two cogwheel holes visible? I should warn you though, as soon as I get an SVG version of this, I'm gonna put it on the website. _Just try to stop me!_

**Comment by badboy** [comment]
Ain't nobody stopping @killercup today.

**Comment by mre** [comment]
<img width="812" alt="grafik" src="https://cloud.githubusercontent.com/assets/175809/23103249/6c7e8e76-f6b8-11e6-8c6a-058dfb3b7052.png">

[Rust-Cologne.zip](https://github.com/Rustaceans/rust-cologne/files/785908/Rust-Cologne.zip)

**Comment by killercup** [comment]
I warned you, didn't I? #25

**Comment by colin-kiegel** [comment]
I prefer the second one. Alternatively I _could_ imagine a variation of No2 with a thin hairline separating the  inner contour of the cogwheel from the background. But I'm not sure if it would really look better. I think it's already quite perfect.

**Comment by killercup** [comment]
@colin-kiegel, don't hover over the logo on rust.cologne :trollface:

**Comment by colin-kiegel** [comment]
Haha, cool. :-) 
I uploaded it to twitter and meetup and postet a tweet
https://twitter.com/RustCologne/status/833366130634977288

**Comment by killercup** [comment]
If anyone needs a larger PNG version of the logo, here's one in 1024x1024:

![rust-cologne](https://cloud.githubusercontent.com/assets/20063/23104656/7d0c1ff0-f6d2-11e6-804b-0ec64564b0d4.png)

**Comment by colin-kiegel** [comment]
I experimented with a bit of orange on our meetup page. The problem is that the meetup logo is red and does _not_ look good close to an orange banner (I tried it, yuck).

Here are seven variations
1: as is
2-4: partially orange logo and/or orange links
5-7: + dark banner

But notice: Red buttons would very likely appear in meetup emails and meetup event pages right next to orange text :worried:. Feels like we can't really switch to orange on meetup. Either keep it blue or pick red - but the mix does not look good when orange and red gets close.

I thought I'd share it anyway, here you go.

![orange_is_the_new_black](https://cloud.githubusercontent.com/assets/7691186/23105579/b713685c-f6e1-11e6-8baa-d3d157ed62ee.png)

![yuck](https://cloud.githubusercontent.com/assets/7691186/23105708/8c3e5752-f6e3-11e6-823d-efc54678177f.png)

**Comment by killercup** [comment]
I'd go with the black logo and keep the blue aqua background color that looks like it's very good at making things rust.

Otherwise: [big red threatening meetup logo](https://cloud.githubusercontent.com/assets/20063/23105804/5c23c654-f6e5-11e6-906a-a6bbf71d27a9.png) for use with grey and with meetup red

**Comment by colin-kiegel** [comment]
Our twitter profile and meetup page had different colors of blue. I switched our twitter color theme to the meetup banner blue. It's only a minor change. You can see it in these screenshots (1 vs 2).

![twitter_blue](https://cloud.githubusercontent.com/assets/7691186/23106158/7bc03372-f6e9-11e6-99ba-0523867c9e3f.png)

I also checked how a black/blue logo would look like on meetup. I'd stick with the black logo for now. It's also more close to the original.

![black_or_blue](https://cloud.githubusercontent.com/assets/7691186/23106172/ba7dff18-f6e9-11e6-994d-fb7dfa801f13.png)

PS: These are our current colours:
- meetup banner: #0095CB (blue)
- meetup links: #2A9BC7 (turquoise)
- website links: #FF7500 (orange)
- plus meetup red #ed1c40 and green #0fd9a3 *sigh*

**Comment by colin-kiegel** [comment]
Looks to me like we can close this. Thx everyone. :-)
