### ISSUE TITLE
Online meetup?

### ISSUE THREAD

**Issue by mre** [Rustaceans/rust-cologne#92]
Was wondering whether we should offer an online "Rust meet-and-greet".
Could be something spontaneous where people talk about their projects and there could be lightning talks.
It's just an idea to revive the meetup. 
@Florob, @uwearzt opinions?

**Comment by cars10** [comment]
+1 :)

**Comment by xetra11** [comment]
Like it - I am back in Cologne and wanted to give Rust a second try. However not possible now since C4 is closed (it is right?) and therefore I'd love to have that meeting in another way again.

**Comment by kawogi** [comment]
I'd be in favour.
We might start with a casual jitsi session, just to see how this works out.
Other opinions on that?

**Comment by mre** [comment]
Well, we can always give it a try. 😄 
For anyone that's interested, could you fill out [the Doodle here](https://doodle.com/poll/zvh4q5fpmxg9yqvp) to find a date?
I'd like to try [gather](https://gather.town) to organize the meetup. It's supposedly a bit more fun/relaxed than a zoom call. Already created a room for us. Check it out here if you want to test your setup:
https://gather.town/app/0Ez2adaJDhN67Xzw/rust

**Comment by kawogi** [comment]
Risking another ping @Florob and @uwearzt ;)

**Comment by mre** [comment]
So far most people seem to prefer 1st of February. I'll leave the poll open in case more people want to chime in.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/175809/105035724-c21aeb80-5a5b-11eb-896d-29e51a1b23b3.png">

**Comment by mre** [comment]
So since we didn't get more participants, I'd say let's go for 1st of February, 7pm at https://gather.town/app/0Ez2adaJDhN67Xzw/rust. Be there or be square. Not sure what we're gonna do yet, but we'll figure it out. I'll also announce it on Twitter for good measure. Bring your friends. ✌️ 
Oh and this is totally an in-official meeting and not endorsed by Rust Cologne. Just a bunch of people talking Rust. 😉

**Comment by mre** [comment]
Just as a summary: the online meetup was quite fun. Gather town was working great; then again we were only four people, so we'll have to see how it works with a bigger group. 
We enjoyed a great presentation by @YtvwlD about his bootloader written in Rust. After that, we were taking turns showing our projects and talking about possible improvements.
Overall, we'd love to do another event like that in the future. We're aiming for 1st of March right now, which coincidentally is another Monday.

Since this is not an official Rust Cologne meetup, I'd like to move the discussion somewhere else. Any suggestions?

**Comment by xetra11** [comment]
Sorry could not participate. Btw. we use Gather for our virtual office and it works fine with 12 people. Just an experience report

**Comment by YtvwlD** [comment]
> We're aiming for 1st of March right now, which coincidentally is another Monday.

But you didn't hit – or am I too late? :D

**Comment by mre** [comment]
@YtvwlD and me decided to move it to *next week on 8th of March*.
We'll organize a temporary online meetup at https://github.com/hello-rust/community.
Feel free to click on the "watch" button to get notified about future events. It's that easy. 😄 
If you want to participate in the next meetup, add a comment here or just be there: https://github.com/hello-rust/community/issues/2
See ya!

**Comment by xetra11** [comment]
@mre 
Consider using the Github Discussions Feature. I think this is more suitable for having "Discussions" :D

**Comment by mre** [comment]
Github discussions didn't exist when this issue was created; and the feature has to be activated for each repo, which it wasn't. 😉 Organization moved to  https://github.com/hello-rust/community now, so I don't expect any further issues here.
