### ISSUE TITLE
Meetup Organizer Subscription - Renewal or drop?

### ISSUE THREAD

**Issue by badboy** [Rustaceans/rust-cologne#94]
Hey,

I've been paying for a meetup.com Organizer Subscription ever since I was hosting the meetup.
This allows to have the https://www.meetup.com/RustCologne/ org running with unlimited members.
I haven't been involved since 2018 though.

The subscription is now up for renewal on October 25th (just 5 days from now) for ~30 eur/6 months.
Canceling means that the group will be up for grabs to a new organizer (or one I hand it over to), probably requiring a organizer subscription too.
Alternatively the group can be closed down fully (see https://help.meetup.com/hc/en-us/articles/360002883151-Canceling-an-organizer-subscription)

It's not too much money really, but if the group goes unused there's no point in paying meetup.com that amount of money, so I'd like to end it.
If I do that there's still 2 additional weeks to make a decision before the group essentially becomes up-for-grabs for anyone, which I'd like to avoid.
Alternatively I can pay once more. Subscriptions can be handed over to others while still running.

If I hear nothing by Sunday (24th) I would cancel it.
I'm not sure who's still involved, and able to make that decision.
cc @Florob @mre @uwearzt

**Comment by badboy** [comment]
Oh, another option: seems @flaki still has a subscription too until April so we could move RustCologne over to his account and have another 6 months to figure this out without paying double.

**Comment by Florob** [comment]
@badboy The meetup group will eventually be used again (cf. https://github.com/Rustaceans/rust-cologne/issues/93#issuecomment-949358662 for the caveats/details of that statement). Feel free to transfer it to me.

**Comment by badboy** [comment]
Done. Thanks for the efforts.

**Comment by Florob** [comment]
Is there a trick to paying ~30€ / 6 month?
They want ~40€ for the first 6 month and about 50€/6 month after that for me.

**Comment by badboy** [comment]
uuuuhm ... Meetup's pricing sucks.
Maybe I'm getting an old price because I've been paying for so long?

What's listed for you here? https://help.meetup.com/hc/en-us/articles/360001620472-Organizer-subscription-pricing

**Comment by badboy** [comment]
Aaaah, huh. I did misread that page the first time. It indeed lists $59.94 per 6 month.
Yet, my account would still pay US$35.63, so I guess they didn't raise prices for old accounts.

With that in mind I'd be willing to just pay up for another 6 months now (and then you owe me a Mate next time I'm in Cologne :P)

**Comment by Florob** [comment]
I'd appreciate that, you can even have two Mates :P.
Let's see if meetup allows that, or if we're caught in some limbo now.

Midterm I'll try to talk to other people doing meetups at the C4. Apparently the cost is per organizer not per meetup after all.

**Comment by badboy** [comment]
You should be able to decline my ask for you to become organizer, or if you already accepted step down as an organizer and assign me again.

A single organizer subscriptions can hold up to 3 meetups.

**Comment by Florob** [comment]
I had accepted, but not filled out payment, hence my fear of limbo. Fortunately it does not require me to pay before I can step down.

**Comment by badboy** [comment]
According to the mail I just got "Your nomination has been declined".
We keep it at that and maybe talk again around January/February to see the next steps for in 6 month.
